// Generated by Haxe 4.0.0-rc.2+2341805c7
(function ($hx_exports, $global) { "use strict";
var $estr = function() { return js_Boot.__string_rec(this,''); },$hxEnums = $hxEnums || {},$_;
function $extend(from, fields) {
	var proto = Object.create(from);
	for (var name in fields) proto[name] = fields[name];
	if( fields.toString !== Object.prototype.toString ) proto.toString = fields.toString;
	return proto;
}
var HxOverrides = function() { };
HxOverrides.__name__ = true;
HxOverrides.cca = function(s,index) {
	var x = s.charCodeAt(index);
	if(x != x) {
		return undefined;
	}
	return x;
};
HxOverrides.substr = function(s,pos,len) {
	if(len == null) {
		len = s.length;
	} else if(len < 0) {
		if(pos == 0) {
			len = s.length + len;
		} else {
			return "";
		}
	}
	return s.substr(pos,len);
};
HxOverrides.iter = function(a) {
	return { cur : 0, arr : a, hasNext : function() {
		return this.cur < this.arr.length;
	}, next : function() {
		return this.arr[this.cur++];
	}};
};
var json2object_reader_BaseParser = function(errors,putils,errorType) {
	this.errors = errors;
	this.putils = putils;
	this.errorType = errorType;
};
json2object_reader_BaseParser.__name__ = true;
json2object_reader_BaseParser.prototype = {
	fromJson: function(jsonString,filename) {
		if(filename == null) {
			filename = "";
		}
		this.putils = new json2object_PositionUtils(jsonString);
		this.errors = [];
		try {
			var json = new hxjsonast_Parser(jsonString,filename).doParse();
			this.loadJson(json);
		} catch( e ) {
			var e1 = ((e) instanceof js__$Boot_HaxeError) ? e.val : e;
			if(((e1) instanceof hxjsonast_Error)) {
				var e2 = e1;
				this.errors.push(json2object_Error.ParserError(e2.message,this.putils.convertPosition(e2.pos)));
			} else {
				throw e;
			}
		}
		return this.value;
	}
	,loadJson: function(json,variable) {
		if(variable == null) {
			variable = "";
		}
		var pos = this.putils.convertPosition(json.pos);
		var _g = json.value;
		switch(_g._hx_index) {
		case 0:
			var s = _g.s;
			this.loadJsonString(s,pos,variable);
			break;
		case 1:
			var n = _g.s;
			this.loadJsonNumber(n,pos,variable);
			break;
		case 2:
			var o = _g.fields;
			this.loadJsonObject(o,pos,variable);
			break;
		case 3:
			var a = _g.values;
			this.loadJsonArray(a,pos,variable);
			break;
		case 4:
			var b = _g.b;
			this.loadJsonBool(b,pos,variable);
			break;
		case 5:
			this.loadJsonNull(pos,variable);
			break;
		}
		return this.value;
	}
	,loadJsonNull: function(pos,variable) {
		this.onIncorrectType(pos,variable);
	}
	,loadJsonString: function(s,pos,variable) {
		this.onIncorrectType(pos,variable);
	}
	,loadString: function(s,pos,variable,validValues,defaultValue) {
		if(validValues.indexOf(s) != -1) {
			return s;
		}
		this.onIncorrectType(pos,variable);
		return defaultValue;
	}
	,loadJsonNumber: function(f,pos,variable) {
		this.onIncorrectType(pos,variable);
	}
	,loadJsonUInt: function(f,pos,variable,value) {
		var uint = 0;
		f = StringTools.trim(f);
		var neg = f.charAt(0) == "-";
		if(neg) {
			f = HxOverrides.substr(f,1,null);
		}
		var hex = StringTools.startsWith(f,"0x");
		if(hex) {
			f = HxOverrides.substr(f,2,null);
		}
		var base = hex ? 16 : 10;
		var pow = 1;
		var i = f.length - 1;
		while(i >= 0) {
			var cur = hex ? Std.parseInt("0x" + f.charAt(i)) : Std.parseInt(f.charAt(i));
			if(cur == null) {
				this.onIncorrectType(pos,variable);
				return value;
			}
			uint = uint + pow * cur;
			pow *= base;
			--i;
		}
		return uint;
	}
	,loadJsonInt: function(f,pos,variable,value) {
		if(Std.parseInt(f) != null && Std.parseInt(f) == parseFloat(f)) {
			return Std.parseInt(f);
		}
		this.onIncorrectType(pos,variable);
		return value;
	}
	,loadJsonFloat: function(f,pos,variable,value) {
		if(Std.parseInt(f) != null) {
			return parseFloat(f);
		}
		this.onIncorrectType(pos,variable);
		return value;
	}
	,loadJsonBool: function(b,pos,variable) {
		this.onIncorrectType(pos,variable);
	}
	,loadJsonArray: function(a,pos,variable) {
		this.onIncorrectType(pos,variable);
	}
	,loadJsonArrayValue: function(a,loadJsonFn,variable) {
		var _g = [];
		var _g1 = 0;
		while(_g1 < a.length) {
			var j = a[_g1];
			++_g1;
			var tmp;
			try {
				tmp = loadJsonFn(j,variable);
			} catch( _ ) {
				var _1 = ((_) instanceof js__$Boot_HaxeError) ? _.val : _;
				if(typeof(_1) == "string") {
					var _2 = _1;
					continue;
				} else {
					throw _;
				}
			}
			_g.push(tmp);
		}
		return _g;
	}
	,loadJsonObject: function(o,pos,variable) {
		this.onIncorrectType(pos,variable);
	}
	,loadObjectField: function(loadJsonFn,field,name,assigned,defaultValue) {
		try {
			var ret = loadJsonFn(field.value,field.name);
			this.mapSet(assigned,name,true);
			return ret;
		} catch( _ ) {
			var _1 = ((_) instanceof js__$Boot_HaxeError) ? _.val : _;
		}
		return defaultValue;
	}
	,loadObjectFieldReflect: function(loadJsonFn,field,name,assigned) {
		try {
			this.value[name] = loadJsonFn(field.value,field.name);
			this.mapSet(assigned,name,true);
		} catch( _ ) {
			var _1 = ((_) instanceof js__$Boot_HaxeError) ? _.val : _;
		}
	}
	,objectSetupAssign: function(assigned,keys,values) {
		var _g = 0;
		var _g1 = keys.length;
		while(_g < _g1) {
			var i = _g++;
			this.mapSet(assigned,keys[i],values[i]);
		}
	}
	,objectErrors: function(assigned,pos) {
		var lastPos = this.putils.convertPosition(new hxjsonast_Position(pos.file,pos.max - 1,pos.max - 1));
		var s = assigned.keys();
		while(s.hasNext()) {
			var s1 = s.next();
			if(!(__map_reserved[s1] != null ? assigned.getReserved(s1) : assigned.h[s1])) {
				this.errors.push(json2object_Error.UninitializedVariable(s1,lastPos));
			}
		}
	}
	,onIncorrectType: function(pos,variable) {
		this.parsingThrow();
	}
	,parsingThrow: function() {
		if(this.errorType != 0) {
			throw new js__$Boot_HaxeError("json2object: parsing throw");
		}
	}
	,objectThrow: function(pos,variable) {
		if(this.errorType == 2) {
			throw new js__$Boot_HaxeError("json2object: parsing throw");
		} else if(this.errorType == 1) {
			this.errors.push(json2object_Error.UninitializedVariable(variable,pos));
		}
	}
	,mapSet: function(map,key,value) {
		if(__map_reserved[key] != null) {
			map.setReserved(key,value);
		} else {
			map.h[key] = value;
		}
	}
};
var JsonParser_$1 = function(errors,putils,errorType) {
	if(errorType == null) {
		errorType = 0;
	}
	json2object_reader_BaseParser.call(this,errors,putils,errorType);
};
JsonParser_$1.__name__ = true;
JsonParser_$1.__super__ = json2object_reader_BaseParser;
JsonParser_$1.prototype = $extend(json2object_reader_BaseParser.prototype,{
	onIncorrectType: function(pos,variable) {
		this.errors.push(json2object_Error.IncorrectType(variable,"{ targets : vshaxeBuild.project.ArrayHandle<vshaxeBuild.project.Target>, ?mainTarget : Null<String>, ?inherit : Null<String>, ?haxelibs : Null<vshaxeBuild.project.ArrayHandle<vshaxeBuild.project.Haxelib>> }",pos));
		json2object_reader_BaseParser.prototype.onIncorrectType.call(this,pos,variable);
	}
	,loadJsonNull: function(pos,variable) {
		this.value = null;
	}
	,loadJsonObject: function(o,pos,variable) {
		var assigned = new haxe_ds_StringMap();
		this.objectSetupAssign(assigned,["haxelibs","inherit","mainTarget","targets"],[true,true,true,false]);
		this.value = this.getAuto();
		var _g = 0;
		while(_g < o.length) {
			var field = o[_g];
			++_g;
			switch(field.name) {
			case "haxelibs":
				this.loadObjectFieldReflect(($_=new JsonParser_$3(this.errors,this.putils,1),$bind($_,$_.loadJson)),field,"haxelibs",assigned);
				break;
			case "inherit":
				this.loadObjectFieldReflect(($_=new JsonParser_$5(this.errors,this.putils,1),$bind($_,$_.loadJson)),field,"inherit",assigned);
				break;
			case "mainTarget":
				this.loadObjectFieldReflect(($_=new JsonParser_$5(this.errors,this.putils,1),$bind($_,$_.loadJson)),field,"mainTarget",assigned);
				break;
			case "targets":
				this.loadObjectFieldReflect(($_=new JsonParser_$6(this.errors,this.putils,1),$bind($_,$_.loadJson)),field,"targets",assigned);
				break;
			default:
				this.errors.push(json2object_Error.UnknownVariable(field.name,this.putils.convertPosition(field.namePos)));
			}
		}
		this.objectErrors(assigned,pos);
	}
	,getAuto: function() {
		return { haxelibs : new JsonParser_$3([],this.putils,0).loadJson(new hxjsonast_Json(hxjsonast_JsonValue.JNull,new hxjsonast_Position("",0,1))), inherit : new JsonParser_$5([],this.putils,0).loadJson(new hxjsonast_Json(hxjsonast_JsonValue.JNull,new hxjsonast_Position("",0,1))), mainTarget : new JsonParser_$5([],this.putils,0).loadJson(new hxjsonast_Json(hxjsonast_JsonValue.JNull,new hxjsonast_Position("",0,1))), targets : new JsonParser_$6([],this.putils,0).loadJson(new hxjsonast_Json(hxjsonast_JsonValue.JNull,new hxjsonast_Position("",0,1)))};
	}
});
var JsonParser_$11 = function(errors,putils,errorType) {
	if(errorType == null) {
		errorType = 0;
	}
	json2object_reader_BaseParser.call(this,errors,putils,errorType);
};
JsonParser_$11.__name__ = true;
JsonParser_$11.__super__ = json2object_reader_BaseParser;
JsonParser_$11.prototype = $extend(json2object_reader_BaseParser.prototype,{
	onIncorrectType: function(pos,variable) {
		this.errors.push(json2object_Error.IncorrectType(variable,"Bool",pos));
		json2object_reader_BaseParser.prototype.onIncorrectType.call(this,pos,variable);
	}
	,loadJsonNull: function(pos,variable) {
		this.value = null;
	}
	,loadJsonBool: function(b,pos,variable) {
		this.value = b;
	}
	,getAuto: function() {
		return new JsonParser_$11([],this.putils,0).loadJson(new hxjsonast_Json(hxjsonast_JsonValue.JNull,new hxjsonast_Position("",0,1)));
	}
});
var JsonParser_$12 = function(errors,putils,errorType) {
	if(errorType == null) {
		errorType = 0;
	}
	json2object_reader_BaseParser.call(this,errors,putils,errorType);
};
JsonParser_$12.__name__ = true;
JsonParser_$12.__super__ = json2object_reader_BaseParser;
JsonParser_$12.prototype = $extend(json2object_reader_BaseParser.prototype,{
	onIncorrectType: function(pos,variable) {
		this.errors.push(json2object_Error.IncorrectType(variable,"String",pos));
		json2object_reader_BaseParser.prototype.onIncorrectType.call(this,pos,variable);
	}
	,loadJsonNull: function(pos,variable) {
		this.value = null;
	}
	,loadJsonString: function(s,pos,variable) {
		this.value = s;
	}
	,getAuto: function() {
		return new JsonParser_$12([],this.putils,0).loadJson(new hxjsonast_Json(hxjsonast_JsonValue.JNull,new hxjsonast_Position("",0,1)));
	}
});
var JsonParser_$14 = function(errors,putils,errorType) {
	if(errorType == null) {
		errorType = 0;
	}
	json2object_reader_BaseParser.call(this,errors,putils,errorType);
};
JsonParser_$14.__name__ = true;
JsonParser_$14.__super__ = json2object_reader_BaseParser;
JsonParser_$14.prototype = $extend(json2object_reader_BaseParser.prototype,{
	onIncorrectType: function(pos,variable) {
		this.errors.push(json2object_Error.IncorrectType(variable,"vshaxeBuild.project.ArrayHandle<String>",pos));
		json2object_reader_BaseParser.prototype.onIncorrectType.call(this,pos,variable);
	}
	,loadJsonNull: function(pos,variable) {
		this.value = null;
	}
	,loadJsonArray: function(a,pos,variable) {
		this.value = this.loadJsonArrayValue(a,($_=new JsonParser_$12(this.errors,this.putils,2),$bind($_,$_.loadJson)),variable);
	}
	,getAuto: function() {
		return new JsonParser_$14([],this.putils,0).loadJson(new hxjsonast_Json(hxjsonast_JsonValue.JNull,new hxjsonast_Position("",0,1)));
	}
});
var JsonParser_$17 = function(errors,putils,errorType) {
	if(errorType == null) {
		errorType = 0;
	}
	json2object_reader_BaseParser.call(this,errors,putils,errorType);
};
JsonParser_$17.__name__ = true;
JsonParser_$17.__super__ = json2object_reader_BaseParser;
JsonParser_$17.prototype = $extend(json2object_reader_BaseParser.prototype,{
	onIncorrectType: function(pos,variable) {
		this.errors.push(json2object_Error.IncorrectType(variable,"{ ?workingDirectory : Null<String>, ?times : Null<Bool>, ?packageName : Null<String>, ?output : Null<vshaxeBuild.project.Output>, ?noInline : Null<Bool>, ?main : Null<String>, ?macros : Null<vshaxeBuild.project.ArrayHandle<String>>, ?haxelibs : Null<vshaxeBuild.project.ArrayHandle<String>>, ?defines : Null<vshaxeBuild.project.ArrayHandle<String>>, ?debug : Null<Bool>, ?deadCodeElimination : Null<vshaxeBuild.project.DeadCodeElimination>, ?classPaths : Null<vshaxeBuild.project.ArrayHandle<String>> }",pos));
		json2object_reader_BaseParser.prototype.onIncorrectType.call(this,pos,variable);
	}
	,loadJsonNull: function(pos,variable) {
		this.value = null;
	}
	,loadJsonObject: function(o,pos,variable) {
		var assigned = new haxe_ds_StringMap();
		this.objectSetupAssign(assigned,["classPaths","deadCodeElimination","debug","defines","haxelibs","macros","main","noInline","output","packageName","times","workingDirectory"],[true,true,true,true,true,true,true,true,true,true,true,true]);
		this.value = this.getAuto();
		var _g = 0;
		while(_g < o.length) {
			var field = o[_g];
			++_g;
			switch(field.name) {
			case "classPaths":
				this.loadObjectFieldReflect(($_=new JsonParser_$14(this.errors,this.putils,1),$bind($_,$_.loadJson)),field,"classPaths",assigned);
				break;
			case "deadCodeElimination":
				this.loadObjectFieldReflect(($_=new JsonParser_$26(this.errors,this.putils,1),$bind($_,$_.loadJson)),field,"deadCodeElimination",assigned);
				break;
			case "debug":
				this.loadObjectFieldReflect(($_=new JsonParser_$11(this.errors,this.putils,1),$bind($_,$_.loadJson)),field,"debug",assigned);
				break;
			case "defines":
				this.loadObjectFieldReflect(($_=new JsonParser_$14(this.errors,this.putils,1),$bind($_,$_.loadJson)),field,"defines",assigned);
				break;
			case "haxelibs":
				this.loadObjectFieldReflect(($_=new JsonParser_$14(this.errors,this.putils,1),$bind($_,$_.loadJson)),field,"haxelibs",assigned);
				break;
			case "macros":
				this.loadObjectFieldReflect(($_=new JsonParser_$14(this.errors,this.putils,1),$bind($_,$_.loadJson)),field,"macros",assigned);
				break;
			case "main":
				this.loadObjectFieldReflect(($_=new JsonParser_$5(this.errors,this.putils,1),$bind($_,$_.loadJson)),field,"main",assigned);
				break;
			case "noInline":
				this.loadObjectFieldReflect(($_=new JsonParser_$11(this.errors,this.putils,1),$bind($_,$_.loadJson)),field,"noInline",assigned);
				break;
			case "output":
				this.loadObjectFieldReflect(($_=new JsonParser_$29(this.errors,this.putils,1),$bind($_,$_.loadJson)),field,"output",assigned);
				break;
			case "packageName":
				this.loadObjectFieldReflect(($_=new JsonParser_$5(this.errors,this.putils,1),$bind($_,$_.loadJson)),field,"packageName",assigned);
				break;
			case "times":
				this.loadObjectFieldReflect(($_=new JsonParser_$11(this.errors,this.putils,1),$bind($_,$_.loadJson)),field,"times",assigned);
				break;
			case "workingDirectory":
				this.value.workingDirectory = this.loadObjectField(($_=new JsonParser_$5(this.errors,this.putils,1),$bind($_,$_.loadJson)),field,"workingDirectory",assigned,this.value.workingDirectory);
				break;
			default:
				this.errors.push(json2object_Error.UnknownVariable(field.name,this.putils.convertPosition(field.namePos)));
			}
		}
		this.objectErrors(assigned,pos);
	}
	,getAuto: function() {
		return { classPaths : new JsonParser_$14([],this.putils,0).loadJson(new hxjsonast_Json(hxjsonast_JsonValue.JNull,new hxjsonast_Position("",0,1))), deadCodeElimination : new JsonParser_$26([],this.putils,0).loadJson(new hxjsonast_Json(hxjsonast_JsonValue.JNull,new hxjsonast_Position("",0,1))), debug : new JsonParser_$11([],this.putils,0).loadJson(new hxjsonast_Json(hxjsonast_JsonValue.JNull,new hxjsonast_Position("",0,1))), defines : new JsonParser_$14([],this.putils,0).loadJson(new hxjsonast_Json(hxjsonast_JsonValue.JNull,new hxjsonast_Position("",0,1))), haxelibs : new JsonParser_$14([],this.putils,0).loadJson(new hxjsonast_Json(hxjsonast_JsonValue.JNull,new hxjsonast_Position("",0,1))), macros : new JsonParser_$14([],this.putils,0).loadJson(new hxjsonast_Json(hxjsonast_JsonValue.JNull,new hxjsonast_Position("",0,1))), main : new JsonParser_$5([],this.putils,0).loadJson(new hxjsonast_Json(hxjsonast_JsonValue.JNull,new hxjsonast_Position("",0,1))), noInline : new JsonParser_$11([],this.putils,0).loadJson(new hxjsonast_Json(hxjsonast_JsonValue.JNull,new hxjsonast_Position("",0,1))), output : new JsonParser_$29([],this.putils,0).loadJson(new hxjsonast_Json(hxjsonast_JsonValue.JNull,new hxjsonast_Position("",0,1))), packageName : new JsonParser_$5([],this.putils,0).loadJson(new hxjsonast_Json(hxjsonast_JsonValue.JNull,new hxjsonast_Position("",0,1))), times : new JsonParser_$11([],this.putils,0).loadJson(new hxjsonast_Json(hxjsonast_JsonValue.JNull,new hxjsonast_Position("",0,1))), workingDirectory : new JsonParser_$5([],this.putils,0).loadJson(new hxjsonast_Json(hxjsonast_JsonValue.JNull,new hxjsonast_Position("",0,1)))};
	}
});
var JsonParser_$20 = function(errors,putils,errorType) {
	if(errorType == null) {
		errorType = 0;
	}
	json2object_reader_BaseParser.call(this,errors,putils,errorType);
};
JsonParser_$20.__name__ = true;
JsonParser_$20.__super__ = json2object_reader_BaseParser;
JsonParser_$20.prototype = $extend(json2object_reader_BaseParser.prototype,{
	onIncorrectType: function(pos,variable) {
		this.errors.push(json2object_Error.IncorrectType(variable,"{ ?targetDependencies : Null<vshaxeBuild.project.ArrayHandle<String>>, ?installCommands : Null<vshaxeBuild.project.ArrayHandle<vshaxeBuild.project.ArrayHandle<String>>>, ?beforeBuildCommands : Null<vshaxeBuild.project.ArrayHandle<vshaxeBuild.project.ArrayHandle<String>>>, ?args : Null<vshaxeBuild.project.Hxml>, ?afterBuildCommands : Null<vshaxeBuild.project.ArrayHandle<vshaxeBuild.project.ArrayHandle<String>>> }",pos));
		json2object_reader_BaseParser.prototype.onIncorrectType.call(this,pos,variable);
	}
	,loadJsonNull: function(pos,variable) {
		this.value = null;
	}
	,loadJsonObject: function(o,pos,variable) {
		var assigned = new haxe_ds_StringMap();
		this.objectSetupAssign(assigned,["afterBuildCommands","args","beforeBuildCommands","installCommands","targetDependencies"],[true,true,true,true,true]);
		this.value = this.getAuto();
		var _g = 0;
		while(_g < o.length) {
			var field = o[_g];
			++_g;
			switch(field.name) {
			case "afterBuildCommands":
				this.loadObjectFieldReflect(($_=new JsonParser_$9(this.errors,this.putils,1),$bind($_,$_.loadJson)),field,"afterBuildCommands",assigned);
				break;
			case "args":
				this.loadObjectFieldReflect(($_=new JsonParser_$17(this.errors,this.putils,1),$bind($_,$_.loadJson)),field,"args",assigned);
				break;
			case "beforeBuildCommands":
				this.loadObjectFieldReflect(($_=new JsonParser_$9(this.errors,this.putils,1),$bind($_,$_.loadJson)),field,"beforeBuildCommands",assigned);
				break;
			case "installCommands":
				this.loadObjectFieldReflect(($_=new JsonParser_$9(this.errors,this.putils,1),$bind($_,$_.loadJson)),field,"installCommands",assigned);
				break;
			case "targetDependencies":
				this.loadObjectFieldReflect(($_=new JsonParser_$14(this.errors,this.putils,1),$bind($_,$_.loadJson)),field,"targetDependencies",assigned);
				break;
			default:
				this.errors.push(json2object_Error.UnknownVariable(field.name,this.putils.convertPosition(field.namePos)));
			}
		}
		this.objectErrors(assigned,pos);
	}
	,getAuto: function() {
		var tmp = new JsonParser_$9([],this.putils,0).loadJson(new hxjsonast_Json(hxjsonast_JsonValue.JNull,new hxjsonast_Position("",0,1)));
		var tmp1 = new JsonParser_$9([],this.putils,0).loadJson(new hxjsonast_Json(hxjsonast_JsonValue.JNull,new hxjsonast_Position("",0,1)));
		var tmp2 = new JsonParser_$9([],this.putils,0).loadJson(new hxjsonast_Json(hxjsonast_JsonValue.JNull,new hxjsonast_Position("",0,1)));
		var tmp3 = new JsonParser_$14([],this.putils,0).loadJson(new hxjsonast_Json(hxjsonast_JsonValue.JNull,new hxjsonast_Position("",0,1)));
		return { afterBuildCommands : tmp, args : { }, beforeBuildCommands : tmp1, installCommands : tmp2, targetDependencies : tmp3};
	}
});
var JsonParser_$26 = function(errors,putils,errorType) {
	if(errorType == null) {
		errorType = 0;
	}
	json2object_reader_BaseParser.call(this,errors,putils,errorType);
};
JsonParser_$26.__name__ = true;
JsonParser_$26.__super__ = json2object_reader_BaseParser;
JsonParser_$26.prototype = $extend(json2object_reader_BaseParser.prototype,{
	onIncorrectType: function(pos,variable) {
		this.value = "std";
		this.errors.push(json2object_Error.IncorrectType(variable,"vshaxeBuild.project.DeadCodeElimination",pos));
		this.objectThrow(pos,variable);
	}
	,loadJsonNull: function(pos,variable) {
		this.value = null;
	}
	,loadJsonString: function(s,pos,variable) {
		this.value = this.loadString(s,pos,variable,["std","full","no"],"std");
	}
	,getAuto: function() {
		return new JsonParser_$26([],this.putils,0).loadJson(new hxjsonast_Json(hxjsonast_JsonValue.JNull,new hxjsonast_Position("",0,1)));
	}
});
var JsonParser_$29 = function(errors,putils,errorType) {
	if(errorType == null) {
		errorType = 0;
	}
	json2object_reader_BaseParser.call(this,errors,putils,errorType);
};
JsonParser_$29.__name__ = true;
JsonParser_$29.__super__ = json2object_reader_BaseParser;
JsonParser_$29.prototype = $extend(json2object_reader_BaseParser.prototype,{
	onIncorrectType: function(pos,variable) {
		this.errors.push(json2object_Error.IncorrectType(variable,"{ target : vshaxeBuild.project.HaxeTarget, ?path : Null<String> }",pos));
		json2object_reader_BaseParser.prototype.onIncorrectType.call(this,pos,variable);
	}
	,loadJsonNull: function(pos,variable) {
		this.value = null;
	}
	,loadJsonObject: function(o,pos,variable) {
		var assigned = new haxe_ds_StringMap();
		this.objectSetupAssign(assigned,["path","target"],[true,false]);
		this.value = this.getAuto();
		var _g = 0;
		while(_g < o.length) {
			var field = o[_g];
			++_g;
			switch(field.name) {
			case "path":
				this.loadObjectFieldReflect(($_=new JsonParser_$5(this.errors,this.putils,1),$bind($_,$_.loadJson)),field,"path",assigned);
				break;
			case "target":
				this.loadObjectFieldReflect(($_=new JsonParser_$32(this.errors,this.putils,1),$bind($_,$_.loadJson)),field,"target",assigned);
				break;
			default:
				this.errors.push(json2object_Error.UnknownVariable(field.name,this.putils.convertPosition(field.namePos)));
			}
		}
		this.objectErrors(assigned,pos);
	}
	,getAuto: function() {
		return { path : new JsonParser_$5([],this.putils,0).loadJson(new hxjsonast_Json(hxjsonast_JsonValue.JNull,new hxjsonast_Position("",0,1))), target : new JsonParser_$32([],this.putils,0).loadJson(new hxjsonast_Json(hxjsonast_JsonValue.JNull,new hxjsonast_Position("",0,1)))};
	}
});
var JsonParser_$3 = function(errors,putils,errorType) {
	if(errorType == null) {
		errorType = 0;
	}
	json2object_reader_BaseParser.call(this,errors,putils,errorType);
};
JsonParser_$3.__name__ = true;
JsonParser_$3.__super__ = json2object_reader_BaseParser;
JsonParser_$3.prototype = $extend(json2object_reader_BaseParser.prototype,{
	onIncorrectType: function(pos,variable) {
		this.errors.push(json2object_Error.IncorrectType(variable,"vshaxeBuild.project.ArrayHandle<vshaxeBuild.project.Haxelib>",pos));
		json2object_reader_BaseParser.prototype.onIncorrectType.call(this,pos,variable);
	}
	,loadJsonNull: function(pos,variable) {
		this.value = null;
	}
	,loadJsonArray: function(a,pos,variable) {
		this.value = this.loadJsonArrayValue(a,($_=new JsonParser_$34(this.errors,this.putils,2),$bind($_,$_.loadJson)),variable);
	}
	,getAuto: function() {
		return new JsonParser_$3([],this.putils,0).loadJson(new hxjsonast_Json(hxjsonast_JsonValue.JNull,new hxjsonast_Position("",0,1)));
	}
});
var JsonParser_$32 = function(errors,putils,errorType) {
	if(errorType == null) {
		errorType = 0;
	}
	json2object_reader_BaseParser.call(this,errors,putils,errorType);
};
JsonParser_$32.__name__ = true;
JsonParser_$32.__super__ = json2object_reader_BaseParser;
JsonParser_$32.prototype = $extend(json2object_reader_BaseParser.prototype,{
	onIncorrectType: function(pos,variable) {
		this.value = "swf";
		this.errors.push(json2object_Error.IncorrectType(variable,"vshaxeBuild.project.HaxeTarget",pos));
		this.objectThrow(pos,variable);
	}
	,loadJsonNull: function(pos,variable) {
		this.value = null;
	}
	,loadJsonString: function(s,pos,variable) {
		this.value = this.loadString(s,pos,variable,["swf","js","neko","php","cpp","cppia","as3","java","python","hl","lua","interp"],"swf");
	}
	,getAuto: function() {
		return new JsonParser_$32([],this.putils,0).loadJson(new hxjsonast_Json(hxjsonast_JsonValue.JNull,new hxjsonast_Position("",0,1)));
	}
});
var JsonParser_$33 = function(errors,putils,errorType) {
	if(errorType == null) {
		errorType = 0;
	}
	json2object_reader_BaseParser.call(this,errors,putils,errorType);
};
JsonParser_$33.__name__ = true;
JsonParser_$33.__super__ = json2object_reader_BaseParser;
JsonParser_$33.prototype = $extend(json2object_reader_BaseParser.prototype,{
	onIncorrectType: function(pos,variable) {
		this.errors.push(json2object_Error.IncorrectType(variable,"Array<String>",pos));
		json2object_reader_BaseParser.prototype.onIncorrectType.call(this,pos,variable);
	}
	,loadJsonNull: function(pos,variable) {
		this.value = null;
	}
	,loadJsonArray: function(a,pos,variable) {
		this.value = this.loadJsonArrayValue(a,($_=new JsonParser_$12(this.errors,this.putils,2),$bind($_,$_.loadJson)),variable);
	}
	,getAuto: function() {
		return new JsonParser_$33([],this.putils,0).loadJson(new hxjsonast_Json(hxjsonast_JsonValue.JNull,new hxjsonast_Position("",0,1)));
	}
});
var JsonParser_$34 = function(errors,putils,errorType) {
	if(errorType == null) {
		errorType = 0;
	}
	json2object_reader_BaseParser.call(this,errors,putils,errorType);
};
JsonParser_$34.__name__ = true;
JsonParser_$34.__super__ = json2object_reader_BaseParser;
JsonParser_$34.prototype = $extend(json2object_reader_BaseParser.prototype,{
	onIncorrectType: function(pos,variable) {
		this.errors.push(json2object_Error.IncorrectType(variable,"{ name : String, installArgs : vshaxeBuild.project.ArrayHandle<String>, ?includeProjectFile : Null<Bool> }",pos));
		json2object_reader_BaseParser.prototype.onIncorrectType.call(this,pos,variable);
	}
	,loadJsonNull: function(pos,variable) {
		this.value = null;
	}
	,loadJsonObject: function(o,pos,variable) {
		var assigned = new haxe_ds_StringMap();
		this.objectSetupAssign(assigned,["includeProjectFile","installArgs","name"],[true,false,false]);
		this.value = this.getAuto();
		var _g = 0;
		while(_g < o.length) {
			var field = o[_g];
			++_g;
			switch(field.name) {
			case "includeProjectFile":
				this.value.includeProjectFile = this.loadObjectField(($_=new JsonParser_$11(this.errors,this.putils,1),$bind($_,$_.loadJson)),field,"includeProjectFile",assigned,this.value.includeProjectFile);
				break;
			case "installArgs":
				this.loadObjectFieldReflect(($_=new JsonParser_$35(this.errors,this.putils,1),$bind($_,$_.loadJson)),field,"installArgs",assigned);
				break;
			case "name":
				this.loadObjectFieldReflect(($_=new JsonParser_$12(this.errors,this.putils,1),$bind($_,$_.loadJson)),field,"name",assigned);
				break;
			default:
				this.errors.push(json2object_Error.UnknownVariable(field.name,this.putils.convertPosition(field.namePos)));
			}
		}
		this.objectErrors(assigned,pos);
	}
	,getAuto: function() {
		return { includeProjectFile : new JsonParser_$11([],this.putils,0).loadJson(new hxjsonast_Json(hxjsonast_JsonValue.JNull,new hxjsonast_Position("",0,1))), installArgs : new JsonParser_$35([],this.putils,0).loadJson(new hxjsonast_Json(hxjsonast_JsonValue.JNull,new hxjsonast_Position("",0,1))), name : new JsonParser_$12([],this.putils,0).loadJson(new hxjsonast_Json(hxjsonast_JsonValue.JNull,new hxjsonast_Position("",0,1)))};
	}
});
var JsonParser_$35 = function(errors,putils,errorType) {
	if(errorType == null) {
		errorType = 0;
	}
	json2object_reader_BaseParser.call(this,errors,putils,errorType);
};
JsonParser_$35.__name__ = true;
JsonParser_$35.__super__ = json2object_reader_BaseParser;
JsonParser_$35.prototype = $extend(json2object_reader_BaseParser.prototype,{
	onIncorrectType: function(pos,variable) {
		this.errors.push(json2object_Error.IncorrectType(variable,"vshaxeBuild.project.ArrayHandle<String>",pos));
		json2object_reader_BaseParser.prototype.onIncorrectType.call(this,pos,variable);
	}
	,loadJsonNull: function(pos,variable) {
		this.value = null;
	}
	,loadJsonArray: function(a,pos,variable) {
		this.value = this.loadJsonArrayValue(a,($_=new JsonParser_$12(this.errors,this.putils,2),$bind($_,$_.loadJson)),variable);
	}
	,getAuto: function() {
		return new JsonParser_$35([],this.putils,0).loadJson(new hxjsonast_Json(hxjsonast_JsonValue.JNull,new hxjsonast_Position("",0,1)));
	}
});
var JsonParser_$5 = function(errors,putils,errorType) {
	if(errorType == null) {
		errorType = 0;
	}
	json2object_reader_BaseParser.call(this,errors,putils,errorType);
};
JsonParser_$5.__name__ = true;
JsonParser_$5.__super__ = json2object_reader_BaseParser;
JsonParser_$5.prototype = $extend(json2object_reader_BaseParser.prototype,{
	onIncorrectType: function(pos,variable) {
		this.errors.push(json2object_Error.IncorrectType(variable,"String",pos));
		json2object_reader_BaseParser.prototype.onIncorrectType.call(this,pos,variable);
	}
	,loadJsonNull: function(pos,variable) {
		this.value = null;
	}
	,loadJsonString: function(s,pos,variable) {
		this.value = s;
	}
	,getAuto: function() {
		return new JsonParser_$5([],this.putils,0).loadJson(new hxjsonast_Json(hxjsonast_JsonValue.JNull,new hxjsonast_Position("",0,1)));
	}
});
var JsonParser_$6 = function(errors,putils,errorType) {
	if(errorType == null) {
		errorType = 0;
	}
	json2object_reader_BaseParser.call(this,errors,putils,errorType);
};
JsonParser_$6.__name__ = true;
JsonParser_$6.__super__ = json2object_reader_BaseParser;
JsonParser_$6.prototype = $extend(json2object_reader_BaseParser.prototype,{
	onIncorrectType: function(pos,variable) {
		this.errors.push(json2object_Error.IncorrectType(variable,"vshaxeBuild.project.ArrayHandle<vshaxeBuild.project.Target>",pos));
		json2object_reader_BaseParser.prototype.onIncorrectType.call(this,pos,variable);
	}
	,loadJsonNull: function(pos,variable) {
		this.value = null;
	}
	,loadJsonArray: function(a,pos,variable) {
		this.value = this.loadJsonArrayValue(a,($_=new JsonParser_$7(this.errors,this.putils,2),$bind($_,$_.loadJson)),variable);
	}
	,getAuto: function() {
		return new JsonParser_$6([],this.putils,0).loadJson(new hxjsonast_Json(hxjsonast_JsonValue.JNull,new hxjsonast_Position("",0,1)));
	}
});
var JsonParser_$7 = function(errors,putils,errorType) {
	if(errorType == null) {
		errorType = 0;
	}
	json2object_reader_BaseParser.call(this,errors,putils,errorType);
};
JsonParser_$7.__name__ = true;
JsonParser_$7.__super__ = json2object_reader_BaseParser;
JsonParser_$7.prototype = $extend(json2object_reader_BaseParser.prototype,{
	onIncorrectType: function(pos,variable) {
		this.errors.push(json2object_Error.IncorrectType(variable,"{ ?targetDependencies : Null<vshaxeBuild.project.ArrayHandle<String>>, name : String, ?installCommands : Null<vshaxeBuild.project.ArrayHandle<vshaxeBuild.project.ArrayHandle<String>>>, ?inherit : Null<String>, ?display : Null<vshaxeBuild.project.TargetArguments>, ?debug : Null<vshaxeBuild.project.TargetArguments>, ?composite : Null<Bool>, ?beforeBuildCommands : Null<vshaxeBuild.project.ArrayHandle<vshaxeBuild.project.ArrayHandle<String>>>, ?args : Null<vshaxeBuild.project.Hxml>, ?afterBuildCommands : Null<vshaxeBuild.project.ArrayHandle<vshaxeBuild.project.ArrayHandle<String>>> }",pos));
		json2object_reader_BaseParser.prototype.onIncorrectType.call(this,pos,variable);
	}
	,loadJsonNull: function(pos,variable) {
		this.value = null;
	}
	,loadJsonObject: function(o,pos,variable) {
		var assigned = new haxe_ds_StringMap();
		this.objectSetupAssign(assigned,["afterBuildCommands","args","beforeBuildCommands","composite","debug","display","inherit","installCommands","name","targetDependencies"],[true,true,true,true,true,true,true,true,false,true]);
		this.value = this.getAuto();
		var _g = 0;
		while(_g < o.length) {
			var field = o[_g];
			++_g;
			switch(field.name) {
			case "afterBuildCommands":
				this.loadObjectFieldReflect(($_=new JsonParser_$9(this.errors,this.putils,1),$bind($_,$_.loadJson)),field,"afterBuildCommands",assigned);
				break;
			case "args":
				this.loadObjectFieldReflect(($_=new JsonParser_$17(this.errors,this.putils,1),$bind($_,$_.loadJson)),field,"args",assigned);
				break;
			case "beforeBuildCommands":
				this.loadObjectFieldReflect(($_=new JsonParser_$9(this.errors,this.putils,1),$bind($_,$_.loadJson)),field,"beforeBuildCommands",assigned);
				break;
			case "composite":
				this.loadObjectFieldReflect(($_=new JsonParser_$11(this.errors,this.putils,1),$bind($_,$_.loadJson)),field,"composite",assigned);
				break;
			case "debug":
				this.loadObjectFieldReflect(($_=new JsonParser_$20(this.errors,this.putils,1),$bind($_,$_.loadJson)),field,"debug",assigned);
				break;
			case "display":
				this.loadObjectFieldReflect(($_=new JsonParser_$20(this.errors,this.putils,1),$bind($_,$_.loadJson)),field,"display",assigned);
				break;
			case "inherit":
				this.loadObjectFieldReflect(($_=new JsonParser_$5(this.errors,this.putils,1),$bind($_,$_.loadJson)),field,"inherit",assigned);
				break;
			case "installCommands":
				this.loadObjectFieldReflect(($_=new JsonParser_$9(this.errors,this.putils,1),$bind($_,$_.loadJson)),field,"installCommands",assigned);
				break;
			case "name":
				this.loadObjectFieldReflect(($_=new JsonParser_$12(this.errors,this.putils,1),$bind($_,$_.loadJson)),field,"name",assigned);
				break;
			case "targetDependencies":
				this.loadObjectFieldReflect(($_=new JsonParser_$14(this.errors,this.putils,1),$bind($_,$_.loadJson)),field,"targetDependencies",assigned);
				break;
			default:
				this.errors.push(json2object_Error.UnknownVariable(field.name,this.putils.convertPosition(field.namePos)));
			}
		}
		this.objectErrors(assigned,pos);
	}
	,getAuto: function() {
		var tmp = new JsonParser_$9([],this.putils,0).loadJson(new hxjsonast_Json(hxjsonast_JsonValue.JNull,new hxjsonast_Position("",0,1)));
		var tmp1 = new JsonParser_$9([],this.putils,0).loadJson(new hxjsonast_Json(hxjsonast_JsonValue.JNull,new hxjsonast_Position("",0,1)));
		var tmp2 = new JsonParser_$11([],this.putils,0).loadJson(new hxjsonast_Json(hxjsonast_JsonValue.JNull,new hxjsonast_Position("",0,1)));
		var tmp3 = new JsonParser_$5([],this.putils,0).loadJson(new hxjsonast_Json(hxjsonast_JsonValue.JNull,new hxjsonast_Position("",0,1)));
		var tmp4 = new JsonParser_$9([],this.putils,0).loadJson(new hxjsonast_Json(hxjsonast_JsonValue.JNull,new hxjsonast_Position("",0,1)));
		var tmp5 = new JsonParser_$12([],this.putils,0).loadJson(new hxjsonast_Json(hxjsonast_JsonValue.JNull,new hxjsonast_Position("",0,1)));
		var tmp6 = new JsonParser_$14([],this.putils,0).loadJson(new hxjsonast_Json(hxjsonast_JsonValue.JNull,new hxjsonast_Position("",0,1)));
		return { afterBuildCommands : tmp, args : { }, beforeBuildCommands : tmp1, composite : tmp2, debug : { }, display : { }, inherit : tmp3, installCommands : tmp4, name : tmp5, targetDependencies : tmp6};
	}
});
var JsonParser_$9 = function(errors,putils,errorType) {
	if(errorType == null) {
		errorType = 0;
	}
	json2object_reader_BaseParser.call(this,errors,putils,errorType);
};
JsonParser_$9.__name__ = true;
JsonParser_$9.__super__ = json2object_reader_BaseParser;
JsonParser_$9.prototype = $extend(json2object_reader_BaseParser.prototype,{
	onIncorrectType: function(pos,variable) {
		this.errors.push(json2object_Error.IncorrectType(variable,"vshaxeBuild.project.ArrayHandle<vshaxeBuild.project.ArrayHandle<String>>",pos));
		json2object_reader_BaseParser.prototype.onIncorrectType.call(this,pos,variable);
	}
	,loadJsonNull: function(pos,variable) {
		this.value = null;
	}
	,loadJsonArray: function(a,pos,variable) {
		this.value = this.loadJsonArrayValue(a,($_=new JsonParser_$33(this.errors,this.putils,2),$bind($_,$_.loadJson)),variable);
	}
	,getAuto: function() {
		return new JsonParser_$9([],this.putils,0).loadJson(new hxjsonast_Json(hxjsonast_JsonValue.JNull,new hxjsonast_Position("",0,1)));
	}
});
Math.__name__ = true;
var Std = function() { };
Std.__name__ = true;
Std.string = function(s) {
	return js_Boot.__string_rec(s,"");
};
Std.parseInt = function(x) {
	var v = parseInt(x, x && x[0]=="0" && (x[1]=="x" || x[1]=="X") ? 16 : 10);
	if(isNaN(v)) {
		return null;
	}
	return v;
};
var StringBuf = function() {
	this.b = "";
};
StringBuf.__name__ = true;
var StringTools = function() { };
StringTools.__name__ = true;
StringTools.startsWith = function(s,start) {
	if(s.length >= start.length) {
		return s.lastIndexOf(start,0) == 0;
	} else {
		return false;
	}
};
StringTools.isSpace = function(s,pos) {
	var c = HxOverrides.cca(s,pos);
	if(!(c > 8 && c < 14)) {
		return c == 32;
	} else {
		return true;
	}
};
StringTools.ltrim = function(s) {
	var l = s.length;
	var r = 0;
	while(r < l && StringTools.isSpace(s,r)) ++r;
	if(r > 0) {
		return HxOverrides.substr(s,r,l - r);
	} else {
		return s;
	}
};
StringTools.rtrim = function(s) {
	var l = s.length;
	var r = 0;
	while(r < l && StringTools.isSpace(s,l - r - 1)) ++r;
	if(r > 0) {
		return HxOverrides.substr(s,0,l - r);
	} else {
		return s;
	}
};
StringTools.trim = function(s) {
	return StringTools.ltrim(StringTools.rtrim(s));
};
var haxe_io_Output = function() { };
haxe_io_Output.__name__ = true;
var _$Sys_FileOutput = function(fd) {
	this.fd = fd;
};
_$Sys_FileOutput.__name__ = true;
_$Sys_FileOutput.__super__ = haxe_io_Output;
_$Sys_FileOutput.prototype = $extend(haxe_io_Output.prototype,{
	writeByte: function(c) {
		js_node_Fs.writeSync(this.fd,String.fromCodePoint(c));
	}
	,writeBytes: function(s,pos,len) {
		var data = s.b;
		return js_node_Fs.writeSync(this.fd,js_node_buffer_Buffer.from(data.buffer,data.byteOffset,s.length),pos,len);
	}
	,writeString: function(s,encoding) {
		js_node_Fs.writeSync(this.fd,s);
	}
	,flush: function() {
		js_node_Fs.fsyncSync(this.fd);
	}
	,close: function() {
		js_node_Fs.closeSync(this.fd);
	}
});
var haxe_io_Input = function() { };
haxe_io_Input.__name__ = true;
haxe_io_Input.prototype = {
	readByte: function() {
		throw new js__$Boot_HaxeError("Not implemented");
	}
	,readBytes: function(s,pos,len) {
		var k = len;
		var b = s.b;
		if(pos < 0 || len < 0 || pos + len > s.length) {
			throw new js__$Boot_HaxeError(haxe_io_Error.OutsideBounds);
		}
		try {
			while(k > 0) {
				b[pos] = this.readByte();
				++pos;
				--k;
			}
		} catch( eof ) {
			var eof1 = ((eof) instanceof js__$Boot_HaxeError) ? eof.val : eof;
			if(((eof1) instanceof haxe_io_Eof)) {
				var eof2 = eof1;
			} else {
				throw eof;
			}
		}
		return len - k;
	}
	,readAll: function(bufsize) {
		if(bufsize == null) {
			bufsize = 16384;
		}
		var buf = new haxe_io_Bytes(new ArrayBuffer(bufsize));
		var total = new haxe_io_BytesBuffer();
		try {
			while(true) {
				var len = this.readBytes(buf,0,bufsize);
				if(len == 0) {
					throw new js__$Boot_HaxeError(haxe_io_Error.Blocked);
				}
				total.addBytes(buf,0,len);
			}
		} catch( e ) {
			var e1 = ((e) instanceof js__$Boot_HaxeError) ? e.val : e;
			if(((e1) instanceof haxe_io_Eof)) {
				var e2 = e1;
			} else {
				throw e;
			}
		}
		return total.getBytes();
	}
};
var _$Sys_FileInput = function(fd) {
	this.fd = fd;
};
_$Sys_FileInput.__name__ = true;
_$Sys_FileInput.__super__ = haxe_io_Input;
_$Sys_FileInput.prototype = $extend(haxe_io_Input.prototype,{
	readByte: function() {
		var buf = new js_node_buffer_Buffer(1);
		try {
			js_node_Fs.readSync(this.fd,buf,0,1,null);
		} catch( e ) {
			var e1 = ((e) instanceof js__$Boot_HaxeError) ? e.val : e;
			if(e1.code == "EOF") {
				throw new js__$Boot_HaxeError(new haxe_io_Eof());
			} else {
				throw new js__$Boot_HaxeError(haxe_io_Error.Custom(e1));
			}
		}
		return buf[0];
	}
	,readBytes: function(s,pos,len) {
		var data = s.b;
		var buf = js_node_buffer_Buffer.from(data.buffer,data.byteOffset,s.length);
		try {
			return js_node_Fs.readSync(this.fd,buf,pos,len,null);
		} catch( e ) {
			var e1 = ((e) instanceof js__$Boot_HaxeError) ? e.val : e;
			if(e1.code == "EOF") {
				throw new js__$Boot_HaxeError(new haxe_io_Eof());
			} else {
				throw new js__$Boot_HaxeError(haxe_io_Error.Custom(e1));
			}
		}
	}
	,close: function() {
		js_node_Fs.closeSync(this.fd);
	}
});
var Vscode = require("vscode");
var haxe_ds_Option = $hxEnums["haxe.ds.Option"] = { __ename__ : true, __constructs__ : ["Some","None"]
	,Some: ($_=function(v) { return {_hx_index:0,v:v,__enum__:"haxe.ds.Option",toString:$estr}; },$_.__params__ = ["v"],$_)
	,None: {_hx_index:1,__enum__:"haxe.ds.Option",toString:$estr}
};
var haxe_ds_StringMap = function() {
	this.h = { };
};
haxe_ds_StringMap.__name__ = true;
haxe_ds_StringMap.prototype = {
	setReserved: function(key,value) {
		if(this.rh == null) {
			this.rh = { };
		}
		this.rh["$" + key] = value;
	}
	,getReserved: function(key) {
		if(this.rh == null) {
			return null;
		} else {
			return this.rh["$" + key];
		}
	}
	,existsReserved: function(key) {
		if(this.rh == null) {
			return false;
		}
		return this.rh.hasOwnProperty("$" + key);
	}
	,keys: function() {
		return HxOverrides.iter(this.arrayKeys());
	}
	,arrayKeys: function() {
		var out = [];
		for( var key in this.h ) {
		if(this.h.hasOwnProperty(key)) {
			out.push(key);
		}
		}
		if(this.rh != null) {
			for( var key in this.rh ) {
			if(key.charCodeAt(0) == 36) {
				out.push(key.substr(1));
			}
			}
		}
		return out;
	}
};
var haxe_io_Bytes = function(data) {
	this.length = data.byteLength;
	this.b = new Uint8Array(data);
	this.b.bufferValue = data;
	data.hxBytes = this;
	data.bytes = this.b;
};
haxe_io_Bytes.__name__ = true;
haxe_io_Bytes.prototype = {
	getString: function(pos,len,encoding) {
		if(pos < 0 || len < 0 || pos + len > this.length) {
			throw new js__$Boot_HaxeError(haxe_io_Error.OutsideBounds);
		}
		if(encoding == null) {
			encoding = haxe_io_Encoding.UTF8;
		}
		var s = "";
		var b = this.b;
		var i = pos;
		var max = pos + len;
		switch(encoding._hx_index) {
		case 0:
			var debug = pos > 0;
			while(i < max) {
				var c = b[i++];
				if(c < 128) {
					if(c == 0) {
						break;
					}
					s += String.fromCodePoint(c);
				} else if(c < 224) {
					var code = (c & 63) << 6 | b[i++] & 127;
					s += String.fromCodePoint(code);
				} else if(c < 240) {
					var c2 = b[i++];
					var code1 = (c & 31) << 12 | (c2 & 127) << 6 | b[i++] & 127;
					s += String.fromCodePoint(code1);
				} else {
					var c21 = b[i++];
					var c3 = b[i++];
					var u = (c & 15) << 18 | (c21 & 127) << 12 | (c3 & 127) << 6 | b[i++] & 127;
					s += String.fromCodePoint(u);
				}
			}
			break;
		case 1:
			while(i < max) {
				var c1 = b[i++] | b[i++] << 8;
				s += String.fromCodePoint(c1);
			}
			break;
		}
		return s;
	}
	,toString: function() {
		return this.getString(0,this.length);
	}
};
var haxe_io_BytesBuffer = function() {
	this.pos = 0;
	this.size = 0;
};
haxe_io_BytesBuffer.__name__ = true;
haxe_io_BytesBuffer.prototype = {
	addBytes: function(src,pos,len) {
		if(pos < 0 || len < 0 || pos + len > src.length) {
			throw new js__$Boot_HaxeError(haxe_io_Error.OutsideBounds);
		}
		if(this.pos + len > this.size) {
			this.grow(len);
		}
		if(this.size == 0) {
			return;
		}
		var sub = new Uint8Array(src.b.buffer,src.b.byteOffset + pos,len);
		this.u8.set(sub,this.pos);
		this.pos += len;
	}
	,grow: function(delta) {
		var req = this.pos + delta;
		var nsize = this.size == 0 ? 16 : this.size;
		while(nsize < req) nsize = nsize * 3 >> 1;
		var nbuf = new ArrayBuffer(nsize);
		var nu8 = new Uint8Array(nbuf);
		if(this.size > 0) {
			nu8.set(this.u8);
		}
		this.size = nsize;
		this.buffer = nbuf;
		this.u8 = nu8;
		this.view = new DataView(this.buffer);
	}
	,getBytes: function() {
		if(this.size == 0) {
			return new haxe_io_Bytes(new ArrayBuffer(0));
		}
		var b = new haxe_io_Bytes(this.buffer);
		b.length = this.pos;
		return b;
	}
};
var haxe_io_Encoding = $hxEnums["haxe.io.Encoding"] = { __ename__ : true, __constructs__ : ["UTF8","RawNative"]
	,UTF8: {_hx_index:0,__enum__:"haxe.io.Encoding",toString:$estr}
	,RawNative: {_hx_index:1,__enum__:"haxe.io.Encoding",toString:$estr}
};
var haxe_io_Eof = function() {
};
haxe_io_Eof.__name__ = true;
haxe_io_Eof.prototype = {
	toString: function() {
		return "Eof";
	}
};
var haxe_io_Error = $hxEnums["haxe.io.Error"] = { __ename__ : true, __constructs__ : ["Blocked","Overflow","OutsideBounds","Custom"]
	,Blocked: {_hx_index:0,__enum__:"haxe.io.Error",toString:$estr}
	,Overflow: {_hx_index:1,__enum__:"haxe.io.Error",toString:$estr}
	,OutsideBounds: {_hx_index:2,__enum__:"haxe.io.Error",toString:$estr}
	,Custom: ($_=function(e) { return {_hx_index:3,e:e,__enum__:"haxe.io.Error",toString:$estr}; },$_.__params__ = ["e"],$_)
};
var haxe_io_Path = function() { };
haxe_io_Path.__name__ = true;
haxe_io_Path.join = function(paths) {
	var paths1 = paths.filter(function(s) {
		if(s != null) {
			return s != "";
		} else {
			return false;
		}
	});
	if(paths1.length == 0) {
		return "";
	}
	var path = paths1[0];
	var _g = 1;
	var _g1 = paths1.length;
	while(_g < _g1) {
		var i = _g++;
		path = haxe_io_Path.addTrailingSlash(path);
		path += paths1[i];
	}
	return haxe_io_Path.normalize(path);
};
haxe_io_Path.normalize = function(path) {
	var slash = "/";
	path = path.split("\\").join(slash);
	if(path == slash) {
		return slash;
	}
	var target = [];
	var _g = 0;
	var _g1 = path.split(slash);
	while(_g < _g1.length) {
		var token = _g1[_g];
		++_g;
		if(token == ".." && target.length > 0 && target[target.length - 1] != "..") {
			target.pop();
		} else if(token == "") {
			if(target.length > 0 || HxOverrides.cca(path,0) == 47) {
				target.push(token);
			}
		} else if(token != ".") {
			target.push(token);
		}
	}
	var tmp = target.join(slash);
	var acc_b = "";
	var colon = false;
	var slashes = false;
	var _g2 = 0;
	var _g3 = tmp.length;
	while(_g2 < _g3) {
		var i = _g2++;
		var _g21 = tmp.charCodeAt(i);
		switch(_g21) {
		case 47:
			if(!colon) {
				slashes = true;
			} else {
				var i1 = _g21;
				colon = false;
				if(slashes) {
					acc_b += "/";
					slashes = false;
				}
				acc_b += String.fromCodePoint(i1);
			}
			break;
		case 58:
			acc_b += ":";
			colon = true;
			break;
		default:
			var i2 = _g21;
			colon = false;
			if(slashes) {
				acc_b += "/";
				slashes = false;
			}
			acc_b += String.fromCodePoint(i2);
		}
	}
	return acc_b;
};
haxe_io_Path.addTrailingSlash = function(path) {
	if(path.length == 0) {
		return "/";
	}
	var c1 = path.lastIndexOf("/");
	var c2 = path.lastIndexOf("\\");
	if(c1 < c2) {
		if(c2 != path.length - 1) {
			return path + "\\";
		} else {
			return path;
		}
	} else if(c1 != path.length - 1) {
		return path + "/";
	} else {
		return path;
	}
};
var hxjsonast_Error = function(message,pos) {
	this.message = message;
	this.pos = pos;
};
hxjsonast_Error.__name__ = true;
var hxjsonast_Json = function(value,pos) {
	this.value = value;
	this.pos = pos;
};
hxjsonast_Json.__name__ = true;
var hxjsonast_JsonValue = $hxEnums["hxjsonast.JsonValue"] = { __ename__ : true, __constructs__ : ["JString","JNumber","JObject","JArray","JBool","JNull"]
	,JString: ($_=function(s) { return {_hx_index:0,s:s,__enum__:"hxjsonast.JsonValue",toString:$estr}; },$_.__params__ = ["s"],$_)
	,JNumber: ($_=function(s) { return {_hx_index:1,s:s,__enum__:"hxjsonast.JsonValue",toString:$estr}; },$_.__params__ = ["s"],$_)
	,JObject: ($_=function(fields) { return {_hx_index:2,fields:fields,__enum__:"hxjsonast.JsonValue",toString:$estr}; },$_.__params__ = ["fields"],$_)
	,JArray: ($_=function(values) { return {_hx_index:3,values:values,__enum__:"hxjsonast.JsonValue",toString:$estr}; },$_.__params__ = ["values"],$_)
	,JBool: ($_=function(b) { return {_hx_index:4,b:b,__enum__:"hxjsonast.JsonValue",toString:$estr}; },$_.__params__ = ["b"],$_)
	,JNull: {_hx_index:5,__enum__:"hxjsonast.JsonValue",toString:$estr}
};
var hxjsonast_JObjectField = function(name,namePos,value) {
	this.name = name;
	this.namePos = namePos;
	this.value = value;
};
hxjsonast_JObjectField.__name__ = true;
var hxjsonast_Parser = function(source,filename) {
	this.source = source;
	this.filename = filename;
	this.pos = 0;
};
hxjsonast_Parser.__name__ = true;
hxjsonast_Parser.parse = function(source,filename) {
	return new hxjsonast_Parser(source,filename).doParse();
};
hxjsonast_Parser.prototype = {
	doParse: function() {
		var result = this.parseRec();
		var c;
		while(true) {
			c = this.source.charCodeAt(this.pos++);
			var c1 = c;
			if(!(c1 == c1)) {
				break;
			}
			switch(c) {
			case 9:case 10:case 13:case 32:
				break;
			default:
				this.invalidChar();
			}
		}
		return result;
	}
	,parseRec: function() {
		while(true) {
			var c = this.source.charCodeAt(this.pos++);
			switch(c) {
			case 9:case 10:case 13:case 32:
				break;
			case 34:
				var save = this.pos;
				var s = this.parseString();
				return new hxjsonast_Json(hxjsonast_JsonValue.JString(s),new hxjsonast_Position(this.filename,save - 1,this.pos));
			case 45:case 48:case 49:case 50:case 51:case 52:case 53:case 54:case 55:case 56:case 57:
				var start = this.pos - 1;
				var minus = c == 45;
				var digit = !minus;
				var zero = c == 48;
				var point = false;
				var e = false;
				var pm = false;
				var end = false;
				while(true) {
					switch(this.source.charCodeAt(this.pos++)) {
					case 43:case 45:
						if(!e || pm) {
							this.invalidNumber(start);
						}
						digit = false;
						pm = true;
						break;
					case 46:
						if(minus || point || e) {
							this.invalidNumber(start);
						}
						digit = false;
						point = true;
						break;
					case 48:
						if(zero && !point) {
							this.invalidNumber(start);
						}
						if(minus) {
							minus = false;
							zero = true;
						}
						digit = true;
						break;
					case 49:case 50:case 51:case 52:case 53:case 54:case 55:case 56:case 57:
						if(zero && !point) {
							this.invalidNumber(start);
						}
						if(minus) {
							minus = false;
						}
						digit = true;
						zero = false;
						break;
					case 69:case 101:
						if(minus || zero || e) {
							this.invalidNumber(start);
						}
						digit = false;
						e = true;
						break;
					default:
						if(!digit) {
							this.invalidNumber(start);
						}
						this.pos--;
						end = true;
					}
					if(end) {
						break;
					}
				}
				var s1 = HxOverrides.substr(this.source,start,this.pos - start);
				return new hxjsonast_Json(hxjsonast_JsonValue.JNumber(s1),new hxjsonast_Position(this.filename,start,this.pos));
			case 91:
				var values = [];
				var comma = null;
				var startPos = this.pos - 1;
				while(true) switch(this.source.charCodeAt(this.pos++)) {
				case 9:case 10:case 13:case 32:
					break;
				case 44:
					if(comma) {
						comma = false;
					} else {
						this.invalidChar();
					}
					break;
				case 93:
					if(comma == false) {
						this.invalidChar();
					}
					return new hxjsonast_Json(hxjsonast_JsonValue.JArray(values),new hxjsonast_Position(this.filename,startPos,this.pos));
				default:
					if(comma) {
						this.invalidChar();
					}
					this.pos--;
					values.push(this.parseRec());
					comma = true;
				}
				break;
			case 102:
				var save1 = this.pos;
				if(this.source.charCodeAt(this.pos++) != 97 || this.source.charCodeAt(this.pos++) != 108 || this.source.charCodeAt(this.pos++) != 115 || this.source.charCodeAt(this.pos++) != 101) {
					this.pos = save1;
					this.invalidChar();
				}
				return new hxjsonast_Json(hxjsonast_JsonValue.JBool(false),new hxjsonast_Position(this.filename,save1 - 1,this.pos));
			case 110:
				var save2 = this.pos;
				if(this.source.charCodeAt(this.pos++) != 117 || this.source.charCodeAt(this.pos++) != 108 || this.source.charCodeAt(this.pos++) != 108) {
					this.pos = save2;
					this.invalidChar();
				}
				return new hxjsonast_Json(hxjsonast_JsonValue.JNull,new hxjsonast_Position(this.filename,save2 - 1,this.pos));
			case 116:
				var save3 = this.pos;
				if(this.source.charCodeAt(this.pos++) != 114 || this.source.charCodeAt(this.pos++) != 117 || this.source.charCodeAt(this.pos++) != 101) {
					this.pos = save3;
					this.invalidChar();
				}
				return new hxjsonast_Json(hxjsonast_JsonValue.JBool(true),new hxjsonast_Position(this.filename,save3 - 1,this.pos));
			case 123:
				var fields = [];
				var names = new haxe_ds_StringMap();
				var field = null;
				var fieldPos = null;
				var comma1 = null;
				var startPos1 = this.pos - 1;
				while(true) switch(this.source.charCodeAt(this.pos++)) {
				case 9:case 10:case 13:case 32:
					break;
				case 34:
					if(field != null || comma1) {
						this.invalidChar();
					}
					var fieldStartPos = this.pos - 1;
					field = this.parseString();
					fieldPos = new hxjsonast_Position(this.filename,fieldStartPos,this.pos);
					if(__map_reserved[field] != null ? names.existsReserved(field) : names.h.hasOwnProperty(field)) {
						throw new js__$Boot_HaxeError(new hxjsonast_Error("Duplicate field name \"" + field + "\"",fieldPos));
					} else if(__map_reserved[field] != null) {
						names.setReserved(field,true);
					} else {
						names.h[field] = true;
					}
					break;
				case 44:
					if(comma1) {
						comma1 = false;
					} else {
						this.invalidChar();
					}
					break;
				case 58:
					if(field == null) {
						this.invalidChar();
					}
					fields.push(new hxjsonast_JObjectField(field,fieldPos,this.parseRec()));
					field = null;
					fieldPos = null;
					comma1 = true;
					break;
				case 125:
					if(field != null || comma1 == false) {
						this.invalidChar();
					}
					return new hxjsonast_Json(hxjsonast_JsonValue.JObject(fields),new hxjsonast_Position(this.filename,startPos1,this.pos));
				default:
					this.invalidChar();
				}
				break;
			default:
				this.invalidChar();
			}
		}
	}
	,parseString: function() {
		var start = this.pos;
		var buf = null;
		while(true) {
			var c = this.source.charCodeAt(this.pos++);
			if(c == 34) {
				break;
			}
			if(c == 92) {
				if(buf == null) {
					buf = new StringBuf();
				}
				var s = this.source;
				var len = this.pos - start - 1;
				buf.b += len == null ? HxOverrides.substr(s,start,null) : HxOverrides.substr(s,start,len);
				c = this.source.charCodeAt(this.pos++);
				switch(c) {
				case 34:case 47:case 92:
					buf.b += String.fromCodePoint(c);
					break;
				case 98:
					buf.b += String.fromCodePoint(8);
					break;
				case 102:
					buf.b += String.fromCodePoint(12);
					break;
				case 110:
					buf.b += String.fromCodePoint(10);
					break;
				case 114:
					buf.b += String.fromCodePoint(13);
					break;
				case 116:
					buf.b += String.fromCodePoint(9);
					break;
				case 117:
					var uc = Std.parseInt("0x" + HxOverrides.substr(this.source,this.pos,4));
					this.pos += 4;
					buf.b += String.fromCodePoint(uc);
					break;
				default:
					throw new js__$Boot_HaxeError(new hxjsonast_Error("Invalid escape sequence \\" + String.fromCodePoint(c),new hxjsonast_Position(this.filename,this.pos - 2,this.pos)));
				}
				start = this.pos;
			} else if(c != c) {
				this.pos--;
				throw new js__$Boot_HaxeError(new hxjsonast_Error("Unclosed string",new hxjsonast_Position(this.filename,start - 1,this.pos)));
			}
		}
		if(buf == null) {
			return HxOverrides.substr(this.source,start,this.pos - start - 1);
		} else {
			var s1 = this.source;
			var len1 = this.pos - start - 1;
			buf.b += len1 == null ? HxOverrides.substr(s1,start,null) : HxOverrides.substr(s1,start,len1);
			return buf.b;
		}
	}
	,parseNumber: function(c) {
		var start = this.pos - 1;
		var minus = c == 45;
		var digit = !minus;
		var zero = c == 48;
		var point = false;
		var e = false;
		var pm = false;
		var end = false;
		while(true) {
			switch(this.source.charCodeAt(this.pos++)) {
			case 43:case 45:
				if(!e || pm) {
					this.invalidNumber(start);
				}
				digit = false;
				pm = true;
				break;
			case 46:
				if(minus || point || e) {
					this.invalidNumber(start);
				}
				digit = false;
				point = true;
				break;
			case 48:
				if(zero && !point) {
					this.invalidNumber(start);
				}
				if(minus) {
					minus = false;
					zero = true;
				}
				digit = true;
				break;
			case 49:case 50:case 51:case 52:case 53:case 54:case 55:case 56:case 57:
				if(zero && !point) {
					this.invalidNumber(start);
				}
				if(minus) {
					minus = false;
				}
				digit = true;
				zero = false;
				break;
			case 69:case 101:
				if(minus || zero || e) {
					this.invalidNumber(start);
				}
				digit = false;
				e = true;
				break;
			default:
				if(!digit) {
					this.invalidNumber(start);
				}
				this.pos--;
				end = true;
			}
			if(end) {
				break;
			}
		}
		var s = HxOverrides.substr(this.source,start,this.pos - start);
		return new hxjsonast_Json(hxjsonast_JsonValue.JNumber(s),new hxjsonast_Position(this.filename,start,this.pos));
	}
	,nextChar: function() {
		return this.source.charCodeAt(this.pos++);
	}
	,mk: function(pos,value) {
		return new hxjsonast_Json(value,pos);
	}
	,mkPos: function(min,max) {
		return new hxjsonast_Position(this.filename,min,max);
	}
	,invalidChar: function() {
		this.pos--;
		throw new js__$Boot_HaxeError(new hxjsonast_Error("Invalid character: " + this.source.charAt(this.pos),new hxjsonast_Position(this.filename,this.pos,this.pos + 1)));
	}
	,invalidNumber: function(start) {
		throw new js__$Boot_HaxeError(new hxjsonast_Error("Invalid number: " + this.source.substring(start,this.pos),new hxjsonast_Position(this.filename,start,this.pos)));
	}
};
var hxjsonast_Position = function(file,min,max) {
	this.file = file;
	this.min = min;
	this.max = max;
};
hxjsonast_Position.__name__ = true;
var js__$Boot_HaxeError = function(val) {
	Error.call(this);
	this.val = val;
	if(Error.captureStackTrace) {
		Error.captureStackTrace(this,js__$Boot_HaxeError);
	}
};
js__$Boot_HaxeError.__name__ = true;
js__$Boot_HaxeError.__super__ = Error;
js__$Boot_HaxeError.prototype = $extend(Error.prototype,{
});
var js_Boot = function() { };
js_Boot.__name__ = true;
js_Boot.__string_rec = function(o,s) {
	if(o == null) {
		return "null";
	}
	if(s.length >= 5) {
		return "<...>";
	}
	var t = typeof(o);
	if(t == "function" && (o.__name__ || o.__ename__)) {
		t = "object";
	}
	switch(t) {
	case "function":
		return "<function>";
	case "object":
		if(o.__enum__) {
			var e = $hxEnums[o.__enum__];
			var n = e.__constructs__[o._hx_index];
			var con = e[n];
			if(con.__params__) {
				s += "\t";
				var tmp = n + "(";
				var _g = [];
				var _g1 = 0;
				var _g2 = con.__params__;
				while(_g1 < _g2.length) {
					var p = _g2[_g1];
					++_g1;
					_g.push(js_Boot.__string_rec(o[p],s));
				}
				return tmp + _g.join(",") + ")";
			} else {
				return n;
			}
		}
		if(((o) instanceof Array)) {
			var str = "[";
			s += "\t";
			var _g3 = 0;
			var _g11 = o.length;
			while(_g3 < _g11) {
				var i = _g3++;
				str += (i > 0 ? "," : "") + js_Boot.__string_rec(o[i],s);
			}
			str += "]";
			return str;
		}
		var tostr;
		try {
			tostr = o.toString;
		} catch( e1 ) {
			var e2 = ((e1) instanceof js__$Boot_HaxeError) ? e1.val : e1;
			return "???";
		}
		if(tostr != null && tostr != Object.toString && typeof(tostr) == "function") {
			var s2 = o.toString();
			if(s2 != "[object Object]") {
				return s2;
			}
		}
		var str1 = "{\n";
		s += "\t";
		var hasp = o.hasOwnProperty != null;
		var k = null;
		for( k in o ) {
		if(hasp && !o.hasOwnProperty(k)) {
			continue;
		}
		if(k == "prototype" || k == "__class__" || k == "__super__" || k == "__interfaces__" || k == "__properties__") {
			continue;
		}
		if(str1.length != 2) {
			str1 += ", \n";
		}
		str1 += s + k + " : " + js_Boot.__string_rec(o[k],s);
		}
		s = s.substring(1);
		str1 += "\n" + s + "}";
		return str1;
	case "string":
		return o;
	default:
		return String(o);
	}
};
var js_node_ChildProcess = require("child_process");
var js_node_Fs = require("fs");
var js_node_buffer_Buffer = require("buffer").Buffer;
var json2object_Error = $hxEnums["json2object.Error"] = { __ename__ : true, __constructs__ : ["IncorrectType","IncorrectEnumValue","InvalidEnumConstructor","UninitializedVariable","UnknownVariable","ParserError"]
	,IncorrectType: ($_=function(variable,expected,pos) { return {_hx_index:0,variable:variable,expected:expected,pos:pos,__enum__:"json2object.Error",toString:$estr}; },$_.__params__ = ["variable","expected","pos"],$_)
	,IncorrectEnumValue: ($_=function(value,expected,pos) { return {_hx_index:1,value:value,expected:expected,pos:pos,__enum__:"json2object.Error",toString:$estr}; },$_.__params__ = ["value","expected","pos"],$_)
	,InvalidEnumConstructor: ($_=function(value,expected,pos) { return {_hx_index:2,value:value,expected:expected,pos:pos,__enum__:"json2object.Error",toString:$estr}; },$_.__params__ = ["value","expected","pos"],$_)
	,UninitializedVariable: ($_=function(variable,pos) { return {_hx_index:3,variable:variable,pos:pos,__enum__:"json2object.Error",toString:$estr}; },$_.__params__ = ["variable","pos"],$_)
	,UnknownVariable: ($_=function(variable,pos) { return {_hx_index:4,variable:variable,pos:pos,__enum__:"json2object.Error",toString:$estr}; },$_.__params__ = ["variable","pos"],$_)
	,ParserError: ($_=function(message,pos) { return {_hx_index:5,message:message,pos:pos,__enum__:"json2object.Error",toString:$estr}; },$_.__params__ = ["message","pos"],$_)
};
var json2object_ErrorUtils = function() { };
json2object_ErrorUtils.__name__ = true;
json2object_ErrorUtils.convertError = function(e) {
	var pos;
	switch(e._hx_index) {
	case 0:
		var _g3 = e.expected;
		var _g2 = e.variable;
		var pos1 = e.pos;
		pos = pos1;
		break;
	case 1:
		var _g11 = e.expected;
		var _g10 = e.value;
		var pos2 = e.pos;
		pos = pos2;
		break;
	case 2:
		var _g6 = e.expected;
		var _g5 = e.value;
		var pos3 = e.pos;
		pos = pos3;
		break;
	case 3:
		var _g = e.variable;
		var pos4 = e.pos;
		pos = pos4;
		break;
	case 4:
		var _g8 = e.variable;
		var pos5 = e.pos;
		pos = pos5;
		break;
	case 5:
		var _g13 = e.message;
		var pos6 = e.pos;
		pos = pos6;
		break;
	}
	var header = "";
	if(pos != null) {
		var file = pos.file == "" ? "line" : "" + pos.file + ":";
		if(pos.lines.length == 1) {
			header = "" + file + pos.lines[0].number + ": characters " + pos.lines[0].start + "-" + pos.lines[0].end + " : ";
		} else if(pos.lines.length > 1) {
			header = "" + file + pos.lines[0].number + ": lines " + pos.lines[0].number + "-" + pos.lines[pos.lines.length - 1].number + " : ";
		}
	}
	switch(e._hx_index) {
	case 0:
		var _g19 = e.pos;
		var expected = e.expected;
		var variable = e.variable;
		return header + ("Variable '" + variable + "' should be of type '" + expected + "'");
	case 1:
		var _g27 = e.pos;
		var expected1 = e.expected;
		var variable1 = e.value;
		return header + ("Identifier '" + variable1 + "' isn't part of '" + expected1 + "'");
	case 2:
		var _g22 = e.pos;
		var expected2 = e.expected;
		var variable2 = e.value;
		return header + ("Enum argument '" + variable2 + "' should be of type '" + expected2 + "'");
	case 3:
		var _g16 = e.pos;
		var variable3 = e.variable;
		return header + ("Variable '" + variable3 + "' should be in the json");
	case 4:
		var _g24 = e.pos;
		var variable4 = e.variable;
		return header + ("Variable '" + variable4 + "' isn't part of the schema");
	case 5:
		var _g29 = e.pos;
		var message = e.message;
		return header + ("Parser error: " + message);
	}
};
json2object_ErrorUtils.convertErrorArray = function(e) {
	return e.map(json2object_ErrorUtils.convertError).join("\n");
};
var json2object_JsonParser = function() { };
json2object_JsonParser.__name__ = true;
var json2object_PositionUtils = function(content) {
	this.linesInfo = [];
	var s = 0;
	var e = 0;
	var i = 0;
	var lineCount = 0;
	while(i < content.length) switch(content.charAt(i)) {
	case "\n":
		e = i;
		this.linesInfo.push({ number : lineCount, start : s, end : e});
		++lineCount;
		++i;
		s = i;
		break;
	case "\r":
		e = i;
		if(content.charAt(i + 1) == "\n") {
			++e;
		}
		this.linesInfo.push({ number : lineCount, start : s, end : e});
		++lineCount;
		i = e + 1;
		s = i;
		break;
	default:
		++i;
	}
	this.linesInfo.push({ number : lineCount, start : s, end : i});
};
json2object_PositionUtils.__name__ = true;
json2object_PositionUtils.prototype = {
	convertPosition: function(position) {
		var file = position.file;
		var min = position.min;
		var max = position.max;
		var pos = { file : file, min : min + 1, max : max + 1, lines : []};
		var lastLine = this.linesInfo.length - 1;
		var bounds_min = 0;
		var bounds_max = lastLine;
		if(min > this.linesInfo[0].end) {
			while(bounds_max > bounds_min) {
				var i = (bounds_min + bounds_max) / 2 | 0;
				var line = this.linesInfo[i];
				if(line.start == min) {
					bounds_min = i;
					bounds_max = i;
				}
				if(line.end < min) {
					bounds_min = i + 1;
				}
				if(line.start > min || line.end >= min && line.start < min) {
					bounds_max = i;
				}
			}
		}
		var _g = bounds_min;
		var _g1 = this.linesInfo.length;
		while(_g < _g1) {
			var i1 = _g++;
			var line1 = this.linesInfo[i1];
			if(line1.start <= min && line1.end >= max) {
				pos.lines.push({ number : line1.number + 1, start : min - line1.start + 1, end : max - line1.start + 1});
				break;
			}
			if(line1.start <= min && min <= line1.end) {
				pos.lines.push({ number : line1.number + 1, start : min - line1.start + 1, end : line1.end + 1});
			}
			if(line1.start <= max && max <= line1.end) {
				pos.lines.push({ number : line1.number + 1, start : line1.start + 1, end : max - line1.start + 1});
			}
			if(line1.start >= max || line1.end >= max) {
				break;
			}
		}
		return pos;
	}
	,revert: function(position) {
		return new hxjsonast_Position(position.file,position.min - 1,position.max - 1);
	}
};
var sys_FileSystem = function() { };
sys_FileSystem.__name__ = true;
sys_FileSystem.exists = function(path) {
	try {
		js_node_Fs.accessSync(path);
		return true;
	} catch( _ ) {
		var _1 = ((_) instanceof js__$Boot_HaxeError) ? _.val : _;
		return false;
	}
};
sys_FileSystem.isDirectory = function(path) {
	try {
		return js_node_Fs.statSync(path).isDirectory();
	} catch( e ) {
		var e1 = ((e) instanceof js__$Boot_HaxeError) ? e.val : e;
		return false;
	}
};
var sys_io_FileInput = function(fd) {
	this.fd = fd;
	this.pos = 0;
};
sys_io_FileInput.__name__ = true;
sys_io_FileInput.__super__ = haxe_io_Input;
sys_io_FileInput.prototype = $extend(haxe_io_Input.prototype,{
	readByte: function() {
		var buf = new js_node_buffer_Buffer(1);
		var bytesRead;
		try {
			bytesRead = js_node_Fs.readSync(this.fd,buf,0,1,this.pos);
		} catch( e ) {
			var e1 = ((e) instanceof js__$Boot_HaxeError) ? e.val : e;
			if(e1.code == "EOF") {
				throw new js__$Boot_HaxeError(new haxe_io_Eof());
			} else {
				throw new js__$Boot_HaxeError(haxe_io_Error.Custom(e1));
			}
		}
		if(bytesRead == 0) {
			throw new js__$Boot_HaxeError(new haxe_io_Eof());
		}
		this.pos++;
		return buf[0];
	}
	,readBytes: function(s,pos,len) {
		var data = s.b;
		var buf = js_node_buffer_Buffer.from(data.buffer,data.byteOffset,s.length);
		var bytesRead;
		try {
			bytesRead = js_node_Fs.readSync(this.fd,buf,pos,len,this.pos);
		} catch( e ) {
			var e1 = ((e) instanceof js__$Boot_HaxeError) ? e.val : e;
			if(e1.code == "EOF") {
				throw new js__$Boot_HaxeError(new haxe_io_Eof());
			} else {
				throw new js__$Boot_HaxeError(haxe_io_Error.Custom(e1));
			}
		}
		if(bytesRead == 0) {
			throw new js__$Boot_HaxeError(new haxe_io_Eof());
		}
		this.pos += bytesRead;
		return bytesRead;
	}
	,close: function() {
		js_node_Fs.closeSync(this.fd);
	}
	,seek: function(p,pos) {
		switch(pos._hx_index) {
		case 0:
			this.pos = p;
			break;
		case 1:
			this.pos += p;
			break;
		case 2:
			this.pos = js_node_Fs.fstatSync(this.fd).size + p;
			break;
		}
	}
	,tell: function() {
		return this.pos;
	}
	,eof: function() {
		return this.pos >= js_node_Fs.fstatSync(this.fd).size;
	}
});
var sys_io_FileOutput = function(fd) {
	this.fd = fd;
	this.pos = 0;
};
sys_io_FileOutput.__name__ = true;
sys_io_FileOutput.__super__ = haxe_io_Output;
sys_io_FileOutput.prototype = $extend(haxe_io_Output.prototype,{
	writeByte: function(b) {
		var buf = new js_node_buffer_Buffer(1);
		buf[0] = b;
		js_node_Fs.writeSync(this.fd,buf,0,1,this.pos);
		this.pos++;
	}
	,writeBytes: function(s,pos,len) {
		var data = s.b;
		var buf = js_node_buffer_Buffer.from(data.buffer,data.byteOffset,s.length);
		var wrote = js_node_Fs.writeSync(this.fd,buf,pos,len,this.pos);
		this.pos += wrote;
		return wrote;
	}
	,close: function() {
		js_node_Fs.closeSync(this.fd);
	}
	,seek: function(p,pos) {
		switch(pos._hx_index) {
		case 0:
			this.pos = p;
			break;
		case 1:
			this.pos += p;
			break;
		case 2:
			this.pos = js_node_Fs.fstatSync(this.fd).size + p;
			break;
		}
	}
	,tell: function() {
		return this.pos;
	}
});
var sys_io_FileSeek = $hxEnums["sys.io.FileSeek"] = { __ename__ : true, __constructs__ : ["SeekBegin","SeekCur","SeekEnd"]
	,SeekBegin: {_hx_index:0,__enum__:"sys.io.FileSeek",toString:$estr}
	,SeekCur: {_hx_index:1,__enum__:"sys.io.FileSeek",toString:$estr}
	,SeekEnd: {_hx_index:2,__enum__:"sys.io.FileSeek",toString:$estr}
};
var vscode_ShellExecution = require("vscode").ShellExecution;
var vscode_Task = require("vscode").Task;
var vscode__$TaskScope_TaskScope_$Impl_$ = require("vscode").TaskScope;
var vshaxe__$ReadOnlyArray_ReadOnlyArray_$Impl_$ = {};
vshaxe__$ReadOnlyArray_ReadOnlyArray_$Impl_$.__name__ = true;
vshaxe__$ReadOnlyArray_ReadOnlyArray_$Impl_$.arrayAccess = function(this1,i) {
	return this1[i];
};
vshaxe__$ReadOnlyArray_ReadOnlyArray_$Impl_$.get = function(this1) {
	return this1.slice();
};
var vshaxeBuild_cli_CliTools = function() {
	this.dryRun = false;
	this.verbose = false;
};
vshaxeBuild_cli_CliTools.__name__ = true;
vshaxeBuild_cli_CliTools.prototype = {
	init: function(verbose,dryRun) {
		this.verbose = verbose;
		this.dryRun = dryRun;
		if(dryRun) {
			this.verbose = true;
		}
	}
	,runCommands: function(commands) {
		var _g = 0;
		var _g1 = vshaxeBuild_project__$Project_ArrayHandle_$Impl_$.get(commands);
		while(_g < _g1.length) {
			var command = _g1[_g];
			++_g;
			this.runCommand(command);
		}
	}
	,runCommand: function(cmd) {
		var command = vshaxeBuild_project__$Project_ArrayHandle_$Impl_$.get(cmd);
		if(command.length == 0) {
			return;
		}
		var executable = command[0];
		command.shift();
		this.run(executable,command);
	}
	,inDir: function(dir,f) {
		var oldCwd = process.cwd();
		this.setCwd(dir);
		f();
		this.setCwd(oldCwd);
	}
	,setCwd: function(dir) {
		if(dir == null || StringTools.trim(dir) == "") {
			return;
		}
		this.println("cd " + dir);
		process.chdir(dir);
	}
	,run: function(command,args) {
		var str = command + " " + args.join(" ");
		this.println(str);
		if(this.dryRun) {
			return;
		}
		var result = args == null ? js_node_ChildProcess.spawnSync(command,{ shell : true, stdio : "inherit"}).status : js_node_ChildProcess.spawnSync(command,args,{ stdio : "inherit"}).status;
		if(result != 0) {
			process.stdout.write(Std.string("'" + str + "' exited with " + result));
			process.stdout.write("\n");
			process.exit(result);
		}
	}
	,println: function(message) {
		if(this.verbose) {
			process.stdout.write(Std.string(message));
			process.stdout.write("\n");
		}
	}
	,exit: function(message,code) {
		if(code == null) {
			code = 0;
		}
		process.stdout.write("VSHaxe Build Tool");
		process.stdout.write("\n");
		process.stdout.write(Std.string(message));
		process.stdout.write("\n");
		process.exit(code);
	}
	,fail: function(message) {
		this.exit(message,1);
	}
	,saveContent: function(path,content) {
		if(this.verbose) {
			this.println("Saving to '" + path + "':\n\n" + content);
		}
		if(!this.dryRun) {
			js_node_Fs.writeFileSync(path,content);
		}
	}
};
var vshaxeBuild_extension_DisplayArgumentsProvider = function(projects,vshaxe) {
	this.description = "Project using VSHaxe-Build command line tools";
	this.projects = projects;
	this.vshaxe = vshaxe;
	vshaxe.registerDisplayArgumentsProvider("VSHaxe-Build",this);
};
vshaxeBuild_extension_DisplayArgumentsProvider.__name__ = true;
vshaxeBuild_extension_DisplayArgumentsProvider.prototype = {
	activate: function(provideArguments) {
		var _e = this.projects;
		var f = function(target,debug,flatten,display,recurse) {
			return vshaxeBuild_project__$ProjectList_ProjectList_$Impl_$.resolveTargetHxml(_e,target,debug,flatten,display,recurse);
		};
		var hxmls = function(target1) {
			return f(target1,true,true,true);
		};
		var hxmls1 = vshaxeBuild_project__$ProjectList_ProjectList_$Impl_$.getTargets(this.projects).map(hxmls);
		var hxml = vshaxeBuild_tools_HxmlTools.mergeHxmls(hxmls1,true,true);
		var $arguments = this.vshaxe.parseHxmlToArguments(this.getHxmlArguments(hxml).join("\n"));
		provideArguments($arguments);
	}
	,deactivate: function() {
	}
	,getHxmlArguments: function(hxml) {
		if(hxml == null) {
			return [];
		}
		var lines = [];
		var _g = 0;
		var _g1 = vshaxeBuild_tools_ArrayTools.filterDuplicates(vshaxeBuild_project__$Project_ArrayHandle_$Impl_$.get(hxml.classPaths),function(e1,e2) {
			return e1 == e2;
		});
		while(_g < _g1.length) {
			var cp = _g1[_g];
			++_g;
			lines.push("-cp " + cp);
		}
		var _g2 = 0;
		var _g3 = vshaxeBuild_tools_ArrayTools.filterDuplicates(vshaxeBuild_project__$Project_ArrayHandle_$Impl_$.get(hxml.defines),function(e11,e21) {
			return e11 == e21;
		});
		while(_g2 < _g3.length) {
			var define = _g3[_g2];
			++_g2;
			lines.push("-D " + define);
		}
		var _g4 = 0;
		var _g5 = vshaxeBuild_tools_ArrayTools.filterDuplicates(vshaxeBuild_project__$Project_ArrayHandle_$Impl_$.get(hxml.haxelibs),function(e12,e22) {
			return e12 == e22;
		});
		while(_g4 < _g5.length) {
			var lib = _g5[_g4];
			++_g4;
			lines.push("-lib " + vshaxeBuild_project__$ProjectList_ProjectList_$Impl_$.resolveHaxelib(this.projects,lib).name);
		}
		if(hxml.debug) {
			lines.push("-debug");
		}
		if(hxml.output != null) {
			lines.push(hxml.output.target == "interp" ? "--interp" : "-" + hxml.output.target + " " + hxml.output.path);
		}
		if(hxml.noInline == true) {
			lines.push("--no-inline");
		}
		if(hxml.times == true) {
			lines.push("--times");
		}
		if(hxml.main != null) {
			lines.push("-main " + hxml.main);
		}
		return lines;
	}
};
var vshaxeBuild_extension_Main = function(context) {
	var wsFolder = Vscode.workspace.workspaceFolders == null ? null : Vscode.workspace.workspaceFolders[0];
	if(wsFolder == null) {
		return;
	}
	var cli = new vshaxeBuild_cli_CliTools();
	var vshaxeBuildDir = Vscode.extensions.getExtension("vshaxe.vshaxe-build").extensionPath;
	var projects = new vshaxeBuild_project_ProjectLoader(cli).load(vshaxeBuildDir,wsFolder.uri.fsPath);
	var vshaxe = Vscode.extensions.getExtension("nadako.vshaxe").exports;
	new vshaxeBuild_extension_DisplayArgumentsProvider(projects,vshaxe);
	new vshaxeBuild_extension_TaskProvider(projects,vshaxe);
};
vshaxeBuild_extension_Main.__name__ = true;
vshaxeBuild_extension_Main.main = $hx_exports["activate"] = function(context) {
	new vshaxeBuild_extension_Main(context);
};
var vshaxeBuild_extension_TaskProvider = function(projects,vshaxe) {
	this.projects = projects;
	this.vshaxe = vshaxe;
	Vscode.tasks.registerTaskProvider("vshaxe-build",this);
};
vshaxeBuild_extension_TaskProvider.__name__ = true;
vshaxeBuild_extension_TaskProvider.prototype = {
	provideTasks: function(token) {
		var tasks = [];
		var _g = 0;
		var _g1 = vshaxeBuild_project__$ProjectList_ProjectList_$Impl_$.getTargets(this.projects);
		while(_g < _g1.length) {
			var target = _g1[_g];
			++_g;
			if(target.name == "empty" || target.name == "vshaxe-node") {
				continue;
			}
			tasks.push(this.createTaskForTarget(target,false));
			if(!target.args.debug) {
				tasks.push(this.createTaskForTarget(target,true));
			}
		}
		if(this.projects.length > 1 && this.projects[1].mainTarget != null) {
			tasks.push(this.createTask("install dependencies",this.projects[1].mainTarget,false,["--mode","install"]));
		}
		return tasks;
	}
	,createTaskForTarget: function(target,debug) {
		var args = [];
		var suffix = "";
		if(!target.args.debug && debug) {
			args.push("--debug");
			suffix = " (debug)";
		}
		return this.createTask(target.name + suffix,target.name,debug,args);
	}
	,createTask: function(name,target,debug,additionalArgs) {
		var definition = { type : "vshaxe-build", target : name};
		var args = ["run","vshaxe-build","--target",target,"--executable",this.vshaxe.haxeExecutable.configuration.executable];
		if(additionalArgs != null) {
			args = args.concat(additionalArgs);
		}
		if(this.vshaxe.displayPort != null && this.vshaxe.enableCompilationServer) {
			args = args.concat(["--connect",Std.string(this.vshaxe.displayPort)]);
		}
		var execution = new vscode_ShellExecution("haxelib",args,{ env : this.vshaxe.haxeExecutable.configuration.env});
		var task = new vscode_Task(definition,vscode__$TaskScope_TaskScope_$Impl_$.Workspace,name,"vshaxe-build",execution,vshaxe__$ReadOnlyArray_ReadOnlyArray_$Impl_$.get(this.vshaxe.problemMatchers));
		task.presentationOptions = this.vshaxe.taskPresentation;
		return task;
	}
	,resolveTask: function(task,token) {
		return task;
	}
};
var vshaxeBuild_project__$Project_ArrayHandle_$Impl_$ = {};
vshaxeBuild_project__$Project_ArrayHandle_$Impl_$.__name__ = true;
vshaxeBuild_project__$Project_ArrayHandle_$Impl_$.get = function(this1) {
	if(this1 == null) {
		return [];
	} else {
		return this1.slice();
	}
};
var vshaxeBuild_project__$ProjectList_ProjectList_$Impl_$ = {};
vshaxeBuild_project__$ProjectList_ProjectList_$Impl_$.__name__ = true;
vshaxeBuild_project__$ProjectList_ProjectList_$Impl_$.get = function(this1,i) {
	return this1[i];
};
vshaxeBuild_project__$ProjectList_ProjectList_$Impl_$.resolveHaxelib = function(this1,name) {
	var loop = null;
	loop = function(projects) {
		var project = HxOverrides.iter(projects);
		while(project.hasNext()) {
			var project1 = project.next();
			var lib = vshaxeBuild_tools_ArrayTools.findNamed(project1.haxelibs,name);
			if(lib != null) {
				return lib;
			}
			var libInSub = loop(project1.subProjects);
			if(libInSub != null) {
				return libInSub;
			}
		}
		return null;
	};
	return loop(this1);
};
vshaxeBuild_project__$ProjectList_ProjectList_$Impl_$.resolveTarget = function(this1,name) {
	var loop = null;
	loop = function(projects) {
		var project = HxOverrides.iter(projects);
		while(project.hasNext()) {
			var project1 = project.next();
			var target = vshaxeBuild_tools_ArrayTools.findNamed(project1.targets,name);
			if(target != null) {
				return target;
			}
			var targetInSub = loop(project1.subProjects);
			if(targetInSub != null) {
				return targetInSub;
			}
		}
		return null;
	};
	return loop(this1);
};
vshaxeBuild_project__$ProjectList_ProjectList_$Impl_$.resolveTargets = function(this1,names) {
	var _e = this1;
	return names.map(function(name) {
		return vshaxeBuild_project__$ProjectList_ProjectList_$Impl_$.resolveTarget(_e,name);
	});
};
vshaxeBuild_project__$ProjectList_ProjectList_$Impl_$.resolveTargetHxml = function(this1,target,debug,flatten,display,recurse) {
	if(recurse == null) {
		recurse = true;
	}
	var hxmls = [target.args];
	if(debug) {
		hxmls.push(target.debug.args);
	}
	if(display) {
		hxmls.push(target.display.args);
	}
	if(recurse) {
		var _g = vshaxeBuild_project__$ProjectList_ProjectList_$Impl_$.resolveParent(this1,target);
		switch(_g._hx_index) {
		case 0:
			var parent = _g.v;
			if(parent != null) {
				var inheritedHxml = vshaxeBuild_project__$ProjectList_ProjectList_$Impl_$.resolveTargetHxml(this1,parent,debug,flatten,display,false);
				if(inheritedHxml != null) {
					hxmls.unshift(inheritedHxml);
				}
			}
			break;
		case 1:
			break;
		}
	}
	if(flatten) {
		var _e = this1;
		var f = function(target1,debug1,flatten1,display1,recurse1) {
			return vshaxeBuild_project__$ProjectList_ProjectList_$Impl_$.resolveTargetHxml(_e,target1,debug1,flatten1,display1,recurse1);
		};
		var debug2 = debug;
		var flatten2 = flatten;
		var display2 = display;
		var dependencyHxmls = function(target2) {
			return f(target2,debug2,flatten2,display2);
		};
		var dependencyHxmls1 = vshaxeBuild_project__$ProjectList_ProjectList_$Impl_$.resolveTargets(this1,vshaxeBuild_project__$Project_ArrayHandle_$Impl_$.get(target.targetDependencies)).map(dependencyHxmls);
		hxmls = hxmls.concat(dependencyHxmls1);
	}
	return vshaxeBuild_tools_HxmlTools.mergeHxmls(hxmls,flatten,debug);
};
vshaxeBuild_project__$ProjectList_ProjectList_$Impl_$.resolveParent = function(this1,target) {
	if(target.inherit != null) {
		return haxe_ds_Option.Some(vshaxeBuild_project__$ProjectList_ProjectList_$Impl_$.resolveTarget(this1,target.inherit));
	}
	var _g = vshaxeBuild_project__$ProjectList_ProjectList_$Impl_$.getTargetOwner(this1,target);
	switch(_g._hx_index) {
	case 0:
		var project = _g.v;
		return haxe_ds_Option.Some(vshaxeBuild_project__$ProjectList_ProjectList_$Impl_$.resolveTarget(this1,project.inherit));
	case 1:
		throw new js__$Boot_HaxeError("unable to find owner of target " + target.name);
	}
};
vshaxeBuild_project__$ProjectList_ProjectList_$Impl_$.flattenProjects = function(this1,project) {
	var projects = [project];
	var _e = this1;
	var projects1 = function(project1) {
		return vshaxeBuild_project__$ProjectList_ProjectList_$Impl_$.flattenProjects(_e,project1);
	};
	projects = projects.concat(vshaxeBuild_tools_ArrayTools.flatten(vshaxeBuild_project__$Project_ArrayHandle_$Impl_$.get(project.subProjects).map(projects1)));
	return projects;
};
vshaxeBuild_project__$ProjectList_ProjectList_$Impl_$.getTargetOwner = function(this1,target) {
	var _g = 0;
	while(_g < this1.length) {
		var project = this1[_g];
		++_g;
		var flattened = vshaxeBuild_project__$ProjectList_ProjectList_$Impl_$.flattenProjects(this1,project);
		var _g1 = 0;
		while(_g1 < flattened.length) {
			var flattenedProject = flattened[_g1];
			++_g1;
			if(vshaxeBuild_tools_ArrayTools.findNamed(flattenedProject.targets,target.name) != null) {
				return haxe_ds_Option.Some(project);
			}
		}
	}
	return haxe_ds_Option.None;
};
vshaxeBuild_project__$ProjectList_ProjectList_$Impl_$.getTargets = function(this1) {
	var targets = [];
	var _g = 0;
	while(_g < this1.length) {
		var project = this1[_g];
		++_g;
		var _g1 = 0;
		var _g11 = vshaxeBuild_project__$Project_ArrayHandle_$Impl_$.get(project.targets);
		while(_g1 < _g11.length) {
			var target = _g11[_g1];
			++_g1;
			targets.push(target);
		}
		targets = targets.concat(vshaxeBuild_project__$ProjectList_ProjectList_$Impl_$.getTargets(vshaxeBuild_project__$Project_ArrayHandle_$Impl_$.get(project.subProjects)));
	}
	return targets;
};
var vshaxeBuild_project_ProjectLoader = function(cli) {
	this.cli = cli;
};
vshaxeBuild_project_ProjectLoader.__name__ = true;
vshaxeBuild_project_ProjectLoader.prototype = {
	load: function(vshaxeBuildDir,cwd) {
		this.cli.setCwd(vshaxeBuildDir);
		var defaults = this.toPlacedProject(vshaxeBuildDir,this.readProjectFile("vshaxe-build-defaults.json"));
		this.cli.setCwd(cwd);
		return [defaults,this.findProjectFiles()];
	}
	,findProjectFiles: function(dir) {
		if(dir == null) {
			dir = ".";
		}
		var lastDir = vshaxeBuild_tools_ArrayTools.idx(dir.split("/"),-1);
		if(this.isDirectoryIgnored(lastDir)) {
			return null;
		}
		var project = null;
		var subProjects = [];
		var _g = 0;
		var _g1 = js_node_Fs.readdirSync(dir);
		while(_g < _g1.length) {
			var file = _g1[_g];
			++_g;
			var fullPath = haxe_io_Path.join([dir,file]);
			if(sys_FileSystem.isDirectory(fullPath)) {
				var subProject = this.findProjectFiles(fullPath);
				if(subProject != null) {
					subProjects.push(subProject);
				}
			} else if(file == "vshaxe-build.json") {
				project = this.toPlacedProject(lastDir,this.readProjectFile(fullPath));
				this.adjustWorkingDirectories(project,dir);
			}
		}
		if(project != null) {
			project.subProjects = subProjects;
			var _g2 = 0;
			var _g3 = vshaxeBuild_project__$Project_ArrayHandle_$Impl_$.get(project.haxelibs);
			while(_g2 < _g3.length) {
				var haxelib = _g3[_g2];
				++_g2;
				if(haxelib.includeProjectFile) {
					var dir1 = vshaxeBuild_tools_HaxelibHelper.getLibraryPath(haxelib.name);
					if(dir1 == null) {
						continue;
					}
					dir1 = haxe_io_Path.join([dir1,".."]);
					this.cli.println("Resolved '" + haxelib.name + "' to '" + dir1 + "'");
					if(sys_FileSystem.exists(dir1)) {
						var subProject1 = this.findProjectFiles(dir1);
						if(subProject1 != null) {
							subProjects.push(subProject1);
						}
					}
				}
			}
		}
		return project;
	}
	,isDirectoryIgnored: function(name) {
		if(["dump","node_modules"].indexOf(name) != -1) {
			return true;
		}
		if(name == "." || name == "..") {
			return false;
		}
		return StringTools.startsWith(name,".");
	}
	,readProjectFile: function(path) {
		this.cli.println("Reading project file '" + path + "'...");
		var parser = new JsonParser_$1();
		var json = parser.fromJson(js_node_Fs.readFileSync(path,{ encoding : "utf8"}),path);
		if(parser.errors.length > 0) {
			this.cli.fail(json2object_ErrorUtils.convertErrorArray(parser.errors));
		}
		return json;
	}
	,toPlacedProject: function(directory,project) {
		return { inherit : project.inherit, mainTarget : project.mainTarget, haxelibs : project.haxelibs, targets : project.targets, directory : directory, subProjects : []};
	}
	,adjustWorkingDirectories: function(project,baseDir) {
		var target = HxOverrides.iter(project.targets);
		while(target.hasNext()) {
			var target1 = target.next();
			var hxml = target1.args;
			if(hxml != null) {
				hxml.workingDirectory = baseDir;
			}
			var hxml1 = target1.debug.args;
			if(hxml1 != null) {
				hxml1.workingDirectory = baseDir;
			}
			var hxml2 = target1.display.args;
			if(hxml2 != null) {
				hxml2.workingDirectory = baseDir;
			}
		}
	}
};
var vshaxeBuild_tools_ArrayTools = function() { };
vshaxeBuild_tools_ArrayTools.__name__ = true;
vshaxeBuild_tools_ArrayTools.filterDuplicates = function(array,filter) {
	var unique = [];
	var _g = 0;
	while(_g < array.length) {
		var element = array[_g];
		++_g;
		var present = false;
		var _g1 = 0;
		while(_g1 < unique.length) {
			var unique1 = unique[_g1];
			++_g1;
			if(filter(unique1,element)) {
				present = true;
			}
		}
		if(!present) {
			unique.push(element);
		}
	}
	return unique;
};
vshaxeBuild_tools_ArrayTools.unique = function(array) {
	return vshaxeBuild_tools_ArrayTools.filterDuplicates(array,function(e1,e2) {
		return e1 == e2;
	});
};
vshaxeBuild_tools_ArrayTools.findNamed = function(a,name) {
	var _g = 0;
	var _g1 = vshaxeBuild_project__$Project_ArrayHandle_$Impl_$.get(a);
	while(_g < _g1.length) {
		var e = _g1[_g];
		++_g;
		if(e.name == name) {
			return e;
		}
	}
	return null;
};
vshaxeBuild_tools_ArrayTools.idx = function(a,i) {
	if(i >= 0) {
		return a[i];
	} else {
		return a[a.length + i];
	}
};
vshaxeBuild_tools_ArrayTools.flatMap = function(array,callback) {
	return vshaxeBuild_tools_ArrayTools.flatten(array.map(callback));
};
vshaxeBuild_tools_ArrayTools.flatten = function(array) {
	return vshaxeBuild_tools_ArrayTools.reduce(array,function(acc,element) {
		return acc.concat(element);
	},[]);
};
vshaxeBuild_tools_ArrayTools.reduce = function(array,f,initial) {
	var _g = 0;
	while(_g < array.length) {
		var v = array[_g];
		++_g;
		initial = f(initial,v);
	}
	return initial;
};
var vshaxeBuild_tools_HaxelibHelper = function() { };
vshaxeBuild_tools_HaxelibHelper.__name__ = true;
vshaxeBuild_tools_HaxelibHelper.getLibraryPath = function(library) {
	var output = vshaxeBuild_tools_HaxelibHelper.getProcessOutput("haxelib",["path",library]);
	var result = null;
	var lines = output.split("\n");
	var _g = 1;
	var _g1 = lines.length;
	while(_g < _g1) {
		var i = _g++;
		if(StringTools.startsWith(lines[i],"-D " + library)) {
			result = StringTools.trim(lines[i - 1]);
		}
	}
	return result;
};
vshaxeBuild_tools_HaxelibHelper.getProcessOutput = function(cmd,args) {
	try {
		var $process = new sys.io.Process(cmd,args);
		var output = "";
		try {
			output = $process.stdout.readAll().toString();
		} catch( _ ) {
			var _1 = ((_) instanceof js__$Boot_HaxeError) ? _.val : _;
		}
		$process.close();
		return output;
	} catch( _2 ) {
		var _3 = ((_2) instanceof js__$Boot_HaxeError) ? _2.val : _2;
		return "";
	}
};
var vshaxeBuild_tools_HxmlTools = function() { };
vshaxeBuild_tools_HxmlTools.__name__ = true;
vshaxeBuild_tools_HxmlTools.mergeHxmls = function(hxmls,flatten,debug) {
	var classPaths = [];
	var defines = [];
	var haxelibs = [];
	var macros = [];
	var debug1 = debug;
	var output = null;
	var deadCodeElimination = null;
	var noInline = false;
	var times = false;
	var main = null;
	var packageName = null;
	var merge = function(hxml) {
		if(hxml == null) {
			return;
		}
		var rawClassPaths = vshaxeBuild_project__$Project_ArrayHandle_$Impl_$.get(hxml.classPaths);
		if(flatten) {
			rawClassPaths = rawClassPaths.map(function(cp) {
				return haxe_io_Path.join([hxml.workingDirectory,cp]);
			});
		}
		classPaths = classPaths.concat(rawClassPaths);
		var defines1 = vshaxeBuild_project__$Project_ArrayHandle_$Impl_$.get(hxml.defines);
		defines = defines.concat(defines1);
		var haxelibs1 = vshaxeBuild_project__$Project_ArrayHandle_$Impl_$.get(hxml.haxelibs);
		haxelibs = haxelibs.concat(haxelibs1);
		var macros1 = vshaxeBuild_project__$Project_ArrayHandle_$Impl_$.get(hxml.macros);
		macros = macros.concat(macros1);
		debug1 = debug1 || hxml.debug;
		if(hxml.output != null) {
			if(hxml.output.target != "interp" || output == null) {
				output = hxml.output;
			}
		}
		if(hxml.deadCodeElimination != null) {
			deadCodeElimination = hxml.deadCodeElimination;
		}
		if(hxml.noInline == true) {
			noInline = true;
		}
		if(hxml.times == true) {
			times = true;
		}
		if(hxml.main != null) {
			main = hxml.main;
		}
		if(hxml.packageName != null) {
			packageName = hxml.packageName;
		}
	};
	var _g = 0;
	while(_g < hxmls.length) {
		var hxml1 = hxmls[_g];
		++_g;
		merge(hxml1);
	}
	return { workingDirectory : "", classPaths : classPaths, defines : defines, haxelibs : haxelibs, macros : macros, debug : debug1, output : output, deadCodeElimination : deadCodeElimination, noInline : noInline, times : times, main : main, packageName : packageName};
};
function $bind(o,m) { if( m == null ) return null; if( m.__id__ == null ) m.__id__ = $global.$haxeUID++; var f; if( o.hx__closures__ == null ) o.hx__closures__ = {}; else f = o.hx__closures__[m.__id__]; if( f == null ) { f = m.bind(o); o.hx__closures__[m.__id__] = f; } return f; }
if(typeof $global.$haxeUID == "undefined") $global.$haxeUID = 0;
if( String.fromCodePoint == null ) String.fromCodePoint = function(c) { return c < 0x10000 ? String.fromCharCode(c) : String.fromCharCode((c>>10)+0xD7C0)+String.fromCharCode((c&0x3FF)+0xDC00); }
String.__name__ = true;
Array.__name__ = true;
var __map_reserved = {};
Object.defineProperty(js__$Boot_HaxeError.prototype,"message",{ get : function() {
	return String(this.val);
}});
js_Boot.__toStr = ({ }).toString;
vshaxeBuild_project_ProjectLoader.PROJECT_FILE = "vshaxe-build.json";
vshaxeBuild_project_ProjectLoader.DEFAULTS_FILE = "vshaxe-build-defaults.json";
})(typeof exports != "undefined" ? exports : typeof window != "undefined" ? window : typeof self != "undefined" ? self : this, typeof window != "undefined" ? window : typeof global != "undefined" ? global : typeof self != "undefined" ? self : this);

//# sourceMappingURL=extension.js.map